export const COMUNIDADES = [
  { nombre: "Andalucía", ITP: 7.0 },
  { nombre: "Aragón", ITP: 8.0 },
  { nombre: "Asturias", ITP: 8.0 },
  { nombre: "Baleares", ITP: 8.0 },
  { nombre: "Canarias", ITP: 6.5 },
  { nombre: "Cantabria", ITP: 8.0 },
  { nombre: "Castilla y León", ITP: 8.0 },
  { nombre: "Castilla-La Mancha", ITP: 8.0 },
  { nombre: "Cataluña", ITP: 10.0 },
  { nombre: "Comunidad Valenciana", ITP: 10.0 },
  { nombre: "Extremadura", ITP: 8.0 },
  { nombre: "Galicia", ITP: 10.0 },
  { nombre: "Madrid", ITP: 6.0 },
  { nombre: "Murcia", ITP: 8.0 },
  { nombre: "Navarra", ITP: 6.0 },
  { nombre: "País Vasco", ITP: 7.0 },
  { nombre: "La Rioja", ITP: 7.0 },
  { nombre: "Ceuta", ITP: 6.0 },
  { nombre: "Melilla", ITP: 6.0 },
]
