// AUTO-GENERADO desde 4_Hipotecas_Espana_condiciones.xlsx — 24 de agosto de 2026.
// Cifras orientativas: mezcla de web oficial (FIPRE/FEIN) y comparadores (ver
// campo fuente). N/D = dato no publicado por la entidad; no se inventan cifras.

export interface OfertaHipoteca {
  banco: string
  categoria: string
  producto: string
  tipo: 'Fija' | 'Variable' | 'Mixta' | 'Fija/Variable' | 'Fija/Variable/Mixta' | 'Variable/Mixta'
  tin: string
  tae: string
  plazoMax: string
  financiacionMax: string
  diferencial: string
  vinculaciones: string
  comisiones: string
  requisitos: string
  fuente: string
  // Valores de la actualización anterior (si la oferta ya existía y las cifras
  // son comparables): la tabla los compara con tin/tae y pinta una flecha roja
  // (subida) o verde (bajada). Al actualizar: mover aquí el tin/tae antiguo.
  tinAnterior?: string
  taeAnterior?: string
}

export const FECHA_DATOS = '24 de agosto de 2026'
// Euríbor asumido en las TAE de esta extracción (las páginas muestran
// currentEuribor de euribor-values.ts, no este valor): última media mensual
// cerrada 2,855% (julio 2026); media provisional de agosto, 2,940%.
export const EURIBOR_REFERENCIA = '2,855% (media de julio de 2026)'

export const OFERTAS_HIPOTECAS: OfertaHipoteca[] = [
  {
    "banco": "CaixaBank",
    "categoria": "Grande",
    "producto": "Hipoteca CasaFácil Fijo",
    "tipo": "Fija",
    "tin": "2,85%",
    "tae": "4,26%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, recibos, tarjeta, seguros hogar y vida (alarma según campaña)",
    "comisiones": "Apertura 0% (habitual); amortización: Límite LCCI (fija: 2% 10 años/1,5% después)",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "CaixaBank",
    "categoria": "Grande",
    "producto": "Hipoteca CasaFácil Mixto",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros, tarjeta",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "CaixaBank",
    "categoria": "Grande",
    "producto": "Hipoteca CasaFácil Variable",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "≈E+0,99% (aprox.) · 1er año fijo",
    "vinculaciones": "Nómina, seguros, tarjeta",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Hipoteca Santander Fija",
    "tipo": "Fija",
    "tin": "≈2,96%",
    "tae": "≈3,65%",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguro de vida, seguro de hogar",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Santander",
    "tipo": "Mixta",
    "tin": "2,19% (tramo fijo)",
    "tae": "3,34% / 3,81%",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "E+0,74% (bonif) / E+1,74% (sin) · Tramo fijo: 5,5 años",
    "vinculaciones": "Nómina, seguros; tramitación 100% online",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN",
    "taeAnterior": "3,73% / 4,21%"
  },
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Hipoteca Santander Variable",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "1er año fijo",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "BBVA",
    "categoria": "Grande",
    "producto": "Hipoteca Fija BBVA",
    "tipo": "Fija",
    "tin": "2,95% (primeros 6 meses)",
    "tae": "3,87%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros hogar y vida",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Verificar TIN resto de vida en FEIN",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "BBVA",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta BBVA",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "BBVA",
    "categoria": "Grande",
    "producto": "Hipoteca Variable BBVA",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "≈E+0,99% (aprox.) · 1er año fijo",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Hipoteca Fija Bonificada",
    "tipo": "Fija",
    "tin": "2,75% / 3,75%",
    "tae": "3,58% / ≈4,23%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% 2ª viv.)",
    "diferencial": "",
    "vinculaciones": "Nómina, seguro vida, seguro hogar, seguro protección de pagos",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Hipoteca Variable Sabadell",
    "tipo": "Variable",
    "tin": "1,50% (1er año) / 2,50% (1er año)",
    "tae": "3,98% / 4,64%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "E+0,50% (bonif) / E+1,50% (sin) · Tramo fijo: 1 año",
    "vinculaciones": "Nómina, seguro vida, hogar y protección de pagos. Revisión semestral",
    "comisiones": "Apertura 0%; amortización: 0,25% primeros 3 años (variable)",
    "requisitos": "",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Sabadell",
    "tipo": "Mixta",
    "tin": "2,10% (5 años) / 1,80% (3 años)",
    "tae": "3,65%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "E+1,00% (5a) / E+0,70% (3a) · Tramo fijo: 3 o 5 años",
    "vinculaciones": "Nómina, seguros. Criterios de aprobación flexibles",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Hipoteca Fija Bankinter",
    "tipo": "Fija",
    "tin": "≈3,20% / ≈4,50%",
    "tae": "≈3,79%",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguro de vida, seguro de hogar",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Hipoteca Variable Bankinter",
    "tipo": "Variable",
    "tin": "2,30% (tramo inicial) / 3,60% (tramo inicial)",
    "tae": "3,66% / 4,66%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "E+0,50% (bonif) / E+1,80% (sin)",
    "vinculaciones": "Cuenta nómina/profesional, seguro vida, seguro hogar, plan de pensiones",
    "comisiones": "Apertura 500 €; amortización: Límite LCCI",
    "requisitos": "Asumen gastos salvo tasación",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Bankinter",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Fija Unicaja",
    "tipo": "Fija",
    "tin": "≈3,15%",
    "tae": "≈3,99%",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros, tarjeta. Gestión 100% online",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Variable Unicaja (nómina +2.000 €)",
    "tipo": "Variable",
    "tin": "1,90% (1er año)",
    "tae": "4,21% / 4,29%",
    "plazoMax": "",
    "financiacionMax": "Hasta 90%",
    "diferencial": "E+0,55% (bonif) / E+1,55% (sin); resto ingresos E+0,65% · Tramo fijo: 1 año",
    "vinculaciones": "Nómina, recibos, tarjeta, seguros hogar y vida, fondos/plan de pensiones",
    "comisiones": "Apertura 0,15%; amortización: Límite LCCI",
    "requisitos": "Condiciones segmentadas por nivel de ingresos",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Unicaja",
    "tipo": "Mixta",
    "tin": "2,75% (tramo fijo, nómina +2.000 €)",
    "tae": "3,84%",
    "plazoMax": "",
    "financiacionMax": "Hasta 90%",
    "diferencial": "E+0,85% · Tramo fijo: 10 años",
    "vinculaciones": "Nómina, seguros, tarjeta",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Abanca",
    "categoria": "Grande",
    "producto": "Hipoteca Mari Carmen Fija",
    "tipo": "Fija",
    "tin": "2,95%",
    "tae": "5,24%",
    "plazoMax": "",
    "financiacionMax": "80%-90%",
    "diferencial": "",
    "vinculaciones": "Nómina, 24 compras con tarjeta/año, 2 seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "TAE elevada por coste de vinculaciones",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Abanca",
    "categoria": "Grande",
    "producto": "Hipoteca Mari Carmen Variable",
    "tipo": "Variable",
    "tin": "2,05% (1er año) / 3,05% (1er año)",
    "tae": "5,11% / 4,43%",
    "plazoMax": "",
    "financiacionMax": "Hasta 90-95%",
    "diferencial": "E+0,60% (bonif) / E+1,60% (sin) · Tramo fijo: 1 año",
    "vinculaciones": "Nómina, seguros, tarjeta. OJO: bonificar sale más caro que no bonificar",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Asume tasación; abierta a negociar financiación",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN",
    "taeAnterior": "5,56% / 4,89%"
  },
  {
    "banco": "Abanca",
    "categoria": "Grande",
    "producto": "Hipoteca Mari Carmen Mixta",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%-90%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Vamos Fija",
    "tipo": "Fija",
    "tin": "2,55% (Rankia: desde 2,30%) / 3,55%",
    "tae": "3,49% (Rankia: desde 3,25%)",
    "plazoMax": "≈25 años",
    "financiacionMax": "80% (95% ≤35 años)",
    "diferencial": "",
    "vinculaciones": "Nómina ≥2.500 €, 3 recibos/2 meses, tarjeta (12 usos/sem), seguro hogar, seguro vida, 75 €/mes a fondo",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "TIN del 1er año igual con o sin bonificación",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Vamos Mixta",
    "tipo": "Mixta",
    "tin": "2,00% (5 años) / 2,10% (10 años)",
    "tae": "3,77-3,80% (5a) / 3,47% (10a)",
    "plazoMax": "",
    "financiacionMax": "80% (95% jóvenes)",
    "diferencial": "E+0,60% (el más bajo del mercado mixto) · Tramo fijo: 5 o 10 años",
    "vinculaciones": "Nómina, hogar, vida, tarjeta, recibos, inversiones",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Vamos Variable",
    "tipo": "Variable",
    "tin": "2,00% (1er año)",
    "tae": "4,25%",
    "plazoMax": "",
    "financiacionMax": "80% (95% ≤35)",
    "diferencial": "E+0,60% · Tramo fijo: 1 año",
    "vinculaciones": "Nómina, seguros, tarjeta, recibos, inversiones",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Grande",
    "producto": "Hipoteca Variable Kutxabank",
    "tipo": "Variable",
    "tin": "1,96% (1er año)",
    "tae": "3,67% / 4,30%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (95% ≤35 años)",
    "diferencial": "E+0,49% (bonif) / E+1,49% (sin) · Tramo fijo: 1 año",
    "vinculaciones": "Nómina ≥3.000 €/mes, plan pensiones/EPSV ≥2.400 €/año, seguro hogar (prima ≈397 €/año)",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Diferencial más bajo del mercado",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Grande",
    "producto": "Hipoteca Fija Kutxabank",
    "tipo": "Fija",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80% (95% ≤35)",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros, plan de pensiones",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Competitiva; cifras exactas no públicas",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Kutxabank",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros, plan de pensiones",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Hipoteca Open Fija",
    "tipo": "Fija",
    "tin": "2,86%",
    "tae": "3,42%",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Vinculación reducida (sin vinculación forzosa fuerte)",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Gestión 100% digital",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Hipoteca Open Mixta",
    "tipo": "Mixta",
    "tin": "2,80% (tramo fijo)",
    "tae": "3,37%",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "E+0,60% · Tramo fijo: 5 años",
    "vinculaciones": "Vinculación reducida",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Gestión 100% digital",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Hipoteca Open Variable",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "≈E+0,60%-0,95% · 1er año fijo",
    "vinculaciones": "Vinculación reducida",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "Hipoteca Naranja Variable",
    "tipo": "Variable",
    "tin": "Personalizado",
    "tae": "Personalizada",
    "plazoMax": "",
    "financiacionMax": "80% (75% 2ª viv.)",
    "diferencial": "desde E+0,85% · 1er año fijo",
    "vinculaciones": "Nómina, seguros; precio personalizado según perfil",
    "comisiones": "Apertura 0%; amortización: Sin comisión amortización parcial",
    "requisitos": "Gestión 100% online",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "Hipoteca Naranja Mixta",
    "tipo": "Mixta",
    "tin": "Personalizado",
    "tae": "Personalizada",
    "plazoMax": "40 años (el más largo)",
    "financiacionMax": "80%",
    "diferencial": "desde E+0,89% (bonif) · Tramo fijo: 5/10/15/20 años",
    "vinculaciones": "Nómina, seguros; mejor TIN con certificado energético A/B/C",
    "comisiones": "Apertura 0%; amortización: Sin comisión amortización parcial",
    "requisitos": "Plazo máximo 40 años",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "Hipoteca Naranja Fija",
    "tipo": "Fija",
    "tin": "Personalizado",
    "tae": "Personalizada",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguro de vida, seguro de hogar",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Precio 100% personalizado",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "EVO Banco",
    "categoria": "Online",
    "producto": "Hipoteca Inteligente Fija",
    "tipo": "Fija",
    "tin": "≈2,45% / ≈2,85%",
    "tae": "≈2,93% / ≈3,12%",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguro hogar, seguro vida (bonificación -0,40%)",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Variante Joven (≤35): TIN inferior",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "EVO Banco",
    "categoria": "Online",
    "producto": "Hipoteca Inteligente Variable",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "≈E+0,60% · 1er año fijo",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "EVO Banco",
    "categoria": "Online",
    "producto": "Hipoteca Inteligente Mixta",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "COINC (Bankinter)",
    "categoria": "Online",
    "producto": "Hipoteca Variable COINC",
    "tipo": "Variable",
    "tin": "2,30% (primeros 3 años)",
    "tae": "≈3,34%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (60% 2ª viv.)",
    "diferencial": "E+0,50% (bonif) / E+0,90% (sin) · Tramo fijo: 3 años",
    "vinculaciones": "Cuenta Nómina/No-Nómina/Profesional de Bankinter (-0,40%)",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "COINC (Bankinter)",
    "categoria": "Online",
    "producto": "Hipoteca Fija COINC",
    "tipo": "Fija",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Cuenta Bankinter",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "COINC (Bankinter)",
    "categoria": "Online",
    "producto": "Hipoteca Mixta COINC",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Cuenta Bankinter",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Pibank",
    "categoria": "Online",
    "producto": "Hipoteca Pibank Mixta",
    "tipo": "Mixta",
    "tin": "1,75% (algún comparador: 1,99%)",
    "tae": "3,22%",
    "plazoMax": "35 años",
    "financiacionMax": "Hasta 90%",
    "diferencial": "E+0,68% · Tramo fijo: 4 años (48 cuotas)",
    "vinculaciones": "SIN vinculaciones (solo cuenta + seguro de daños)",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Un titular con contrato indefinido o funcionario",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Pibank",
    "categoria": "Online",
    "producto": "Hipoteca Sin Comisiones Fija",
    "tipo": "Fija",
    "tin": "≈3,11%",
    "tae": "≈3,11%",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "SIN vinculaciones",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Pibank",
    "categoria": "Online",
    "producto": "Hipoteca Pibank Variable",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "1er año fijo",
    "vinculaciones": "SIN vinculaciones",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "MyInvestor",
    "categoria": "Online",
    "producto": "Hipoteca Sin Mochila Variable",
    "tipo": "Variable",
    "tin": "2,75% (1er año)",
    "tae": "3,81%",
    "plazoMax": "",
    "financiacionMax": "Hasta 80%",
    "diferencial": "E+0,79% · Tramo fijo: 1 año",
    "vinculaciones": "SIN vinculaciones (modalidad única)",
    "comisiones": "Apertura 0%; amortización: Sin comisión (asume gastos)",
    "requisitos": "Ingresos netos ≥4.000 €/mes por unidad familiar",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "MyInvestor",
    "categoria": "Online",
    "producto": "Hipoteca Sin Mochila Fija",
    "tipo": "Fija",
    "tin": "desde ≈3,10%",
    "tae": "≈3,38%",
    "plazoMax": "",
    "financiacionMax": "Hasta 80%",
    "diferencial": "",
    "vinculaciones": "SIN vinculaciones",
    "comisiones": "Apertura 0%; amortización: Sin penalización amortización",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "MyInvestor",
    "categoria": "Online",
    "producto": "Hipoteca Sin Mochila Mixta",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "Hasta 80%",
    "diferencial": "",
    "vinculaciones": "SIN vinculaciones",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Hipotecas.com / UCI",
    "categoria": "Online",
    "producto": "Hipoteca Hipotecas.com Fija",
    "tipo": "Fija",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "Elevada (especialista)",
    "diferencial": "",
    "vinculaciones": "Según estudio; especialista en perfiles no atendidos por banca tradicional",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Financiación elevada",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Hipotecas.com / UCI",
    "categoria": "Online",
    "producto": "Hipoteca Hipotecas.com Mixta",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "Elevada",
    "diferencial": "",
    "vinculaciones": "Según estudio",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Hipotecas.com / UCI",
    "categoria": "Online",
    "producto": "Hipoteca Hipotecas.com Variable",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "Elevada",
    "diferencial": "1er año fijo",
    "vinculaciones": "Según estudio",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Banca March (Avantio)",
    "categoria": "Mediano",
    "producto": "Hipoteca Fija Avantio",
    "tipo": "Fija",
    "tin": "2,65%",
    "tae": "3,01% (la TAE más baja del mercado)",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% 2ª viv.)",
    "diferencial": "",
    "vinculaciones": "Nómina ≥2.000 €, seguro de vida, seguro de daños/hogar",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Importe mínimo 200.000 € (nueva) / 150.000 € (subrogación); solo residentes",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Banca March (Avantio)",
    "categoria": "Mediano",
    "producto": "Hipoteca Avantio Mixta",
    "tipo": "Mixta",
    "tin": "2,25% (tramo fijo)",
    "tae": "desde 2,84%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "E+0,60% (bonif) / E+1,30% (sin) · Tramo fijo: 10 años",
    "vinculaciones": "Nómina, seguros. Perfil de alta solvencia",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Importe mínimo elevado",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Banca March (Avantio)",
    "categoria": "Mediano",
    "producto": "Hipoteca Avantio Variable",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "1er año fijo",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Apertura 0%; amortización: Límite LCCI",
    "requisitos": "Importe mínimo elevado",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Targobank",
    "categoria": "Mediano",
    "producto": "Hipoteca Targobank",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Según perfil y oficina",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Comercializa las tres modalidades; cifras no públicas",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Deutsche Bank España",
    "categoria": "Mediano",
    "producto": "Hipoteca Deutsche Bank",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "≈E+1,00% (histórico, variable)",
    "vinculaciones": "Según perfil",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Comercializa las tres modalidades; cifras actuales no públicas",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Cajasur Banco",
    "categoria": "Mediano",
    "producto": "Hipoteca Cajasur",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros, plan de pensiones (similar a Kutxabank)",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Grupo Kutxabank (ámbito Andalucía)",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Banco Mediolanum",
    "categoria": "Mediano",
    "producto": "Hipoteca Mediolanum",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Para clientes de banca personal",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Cifras no públicas",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Banco Pichincha España",
    "categoria": "Mediano",
    "producto": "Hipoteca Banco Pichincha",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Ver condiciones de Pibank (su marca digital)",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Oferta de marca directa no pública",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Banco Caminos / Bancofar",
    "categoria": "Mediano",
    "producto": "Hipoteca Banco Caminos",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Colectivos profesionales (ingenieros de caminos, farmacéuticos...)",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Cifras no públicas",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Caja de Ingenieros",
    "categoria": "Mediano",
    "producto": "Hipoteca Caja de Ingenieros",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Para socios; según perfil",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Cooperativa de crédito",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Arquia Banca",
    "categoria": "Mediano",
    "producto": "Hipoteca Arquia",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Orientada a profesionales colegiados",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Cooperativa de crédito",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Cajamar Caja Rural",
    "categoria": "Cooperativa",
    "producto": "HipotecON Fija",
    "tipo": "Fija",
    "tin": "2,85%",
    "tae": "3,44%",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Cajamar Caja Rural",
    "categoria": "Cooperativa",
    "producto": "HipotecON Variable",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "1er año fijo",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Según perfil y comunidad",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Cajamar Caja Rural",
    "categoria": "Cooperativa",
    "producto": "HipotecON Mixta",
    "tipo": "Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Según perfil y comunidad",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Grupo Caja Rural (Ruralvía)",
    "categoria": "Cooperativa",
    "producto": "Hipoteca Caja Rural (todas las cajas del grupo)",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "≈80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros hogar y vida, a veces plan de pensiones",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Incluye Caja Rural de Navarra, del Sur, Granada, Asturias, Bantierra, Zamora, Soria, Teruel, Extremadura, Salamanca, Central, Jaén, Cajaviva, Eurocaja Rural, Globalcaja, Cajasiete, Caixa Popular, Caixa Rural Galega, Cajalmendralejo, Caja Rural de Utrera, etc. Tipos por oficina/CCAA; no homogéneos",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Hipoteca Mixta Laboral Kutxa",
    "tipo": "Mixta",
    "tin": "1,50% (tramo fijo)",
    "tae": "Personalizada",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "E+0,60% · Tramo fijo: 5 años",
    "vinculaciones": "Nómina, seguro hogar, seguro vida, plan de pensiones",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Modelo cooperativo; TAE tras estudio",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Hipoteca Fija Laboral Kutxa",
    "tipo": "Fija",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros, plan de pensiones",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Hipoteca Variable Laboral Kutxa",
    "tipo": "Variable",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "1er año fijo",
    "vinculaciones": "Nómina, seguros, plan de pensiones",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Caixa Ontinyent / Colonya Caixa Pollença",
    "categoria": "Cooperativa",
    "producto": "Hipoteca (cajas de ahorros regionales)",
    "tipo": "Fija/Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Nómina, seguros",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Ámbito regional (C. Valenciana / Baleares); cifras no públicas",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  },
  {
    "banco": "Triodos Bank",
    "categoria": "Banca ética",
    "producto": "Hipoteca Triodos",
    "tipo": "Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "N/D (bonif. por eficiencia energética)",
    "vinculaciones": "Tipo bonificado según calificación energética de la vivienda",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "Criterios de sostenibilidad; cifras no públicas",
    "fuente": "Comparadores + web oficial de la entidad, 24/08/2026"
  },
  {
    "banco": "Fiare Banca Ética",
    "categoria": "Banca ética",
    "producto": "Financiación hipotecaria Fiare",
    "tipo": "Variable/Mixta",
    "tin": "",
    "tae": "",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Orientada a proyectos con impacto social",
    "comisiones": "Amortización: Límite LCCI",
    "requisitos": "No comercializa hipoteca minorista estándar de forma masiva",
    "fuente": "Comparadores (Rankia, El blog del Euríbor…), 24/08/2026 — verificar en FIPRE/FEIN"
  }
]

// Entidades consultadas que no comercializan hipoteca minorista estándar
// (fuente: notas metodológicas de la extracción del 24/08/2026).
export const ENTIDADES_SIN_OFERTA: { banco: string; nota: string }[] = [
  {
    "banco": "imagin",
    "nota": "Deriva a la hipoteca de CaixaBank (no tiene producto hipotecario propio)"
  },
  {
    "banco": "N26",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Revolut",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Trade Republic",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Bunq",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Wizink",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Banco Cetelem",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Singular Bank",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Andbank España",
    "nota": "Financiación a medida para clientes de banca privada; sin hipoteca minorista estándar"
  },
  {
    "banco": "Bankoa",
    "nota": "Integrado en Abanca"
  },
  {
    "banco": "Banco Cooperativo Español",
    "nota": "Banco mayorista del Grupo Caja Rural; no opera con particulares"
  },
  {
    "banco": "Banco BPI",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Novo Banco",
    "nota": "No comercializa hipoteca minorista estándar en España"
  },
  {
    "banco": "Bank of China / ICBC",
    "nota": "Actividad corporativa; sin hipoteca minorista estándar en España"
  },
  {
    "banco": "Coop57",
    "nota": "Cooperativa de servicios financieros para entidades de economía social; no da hipotecas a particulares"
  }
]
