// AUTO-GENERADO desde comparativa_hipotecas_bancos_espana.xlsx — 13 de julio de 2026.
// Cifras orientativas: mezcla de FIPRE/web oficial y comparadores (ver campo fuente).

export interface OfertaHipoteca {
  banco: string
  categoria: string
  producto: string
  tipo: 'Fija' | 'Variable' | 'Mixta' | 'Fija/Variable'
  tin: string
  tae: string
  plazoMax: string
  financiacionMax: string
  diferencial: string
  vinculaciones: string
  comisiones: string
  requisitos: string
  fuente: string
  // Valores de la actualización anterior (si la oferta ya existía): la tabla
  // los compara con tin/tae y pinta una flecha roja (subida) o verde (bajada).
  // Al actualizar datos: mover el tin/tae antiguo aquí antes de sobreescribir.
  tinAnterior?: string
  taeAnterior?: string
}

export const FECHA_DATOS = '13 de julio de 2026'
export const EURIBOR_REFERENCIA = '2,798% (media de junio de 2026)'

export const OFERTAS_HIPOTECAS: OfertaHipoteca[] = [
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Fija Bonificada",
    "tipo": "Fija",
    "tin": "2,96% / 3,96%",
    "tae": "3,65% / 4,16%",
    "plazoMax": "30 años (25 2ª resid.)",
    "financiacionMax": "80% (70% 2ª)",
    "diferencial": "",
    "vinculaciones": "Máx −1,00% desde mes 7: nómina ≥1.000€/pensión ≥600€ + Bizum o 6 usos tarjeta (−0,50%); seguro hogar prima >300€ (−0,20%); seguro protección préstamos prima >300€ (−0,30%); vida/accidentes/salud/auto prima >200€ (−0,10% c/u); inversión/previsión ≥10.000€ (−0,10%, máx −0,30%)",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (después), máx pérdida financiera",
    "requisitos": "Importe mín. 20.000€; banco paga gastos de constitución salvo tasación; plazo+edad ≤80 años; online. Oferta hasta 15-ago-2026",
    "fuente": "Web oficial bancosantander.es + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Variable Bonificada",
    "tipo": "Variable",
    "tin": "Eur+0,84% / Eur+1,84%",
    "tae": "4,28% / 4,77%",
    "plazoMax": "30 años (25 2ª resid.)",
    "financiacionMax": "80% (70% 2ª)",
    "diferencial": "Euríbor +0,84% (bonif.) / +1,84% (sin bonif.) tras 6 meses; revisión anual",
    "vinculaciones": "Máx −1,00% desde mes 7 (idéntico a la fija): nómina+Bizum/tarjeta (−0,50%); protección préstamos (−0,30%); hogar (−0,20%); vida/accidentes/salud/auto (−0,10%); ahorro/inversión ≥10.000€ (−0,10%, máx −0,30%)",
    "comisiones": "Apertura 0%; amortización 0,25% (3 primeros años) o 0,15% (5 primeros años), máx pérdida financiera",
    "requisitos": "Importe mín. 20.000€; online; sin cláusula suelo. Oferta hasta 15-jul-2026",
    "fuente": "Web oficial bancosantander.es + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Mixta Bonificada",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,34% / 3,34%",
    "tae": "3,73% / 4,21%",
    "plazoMax": "30 años (25 2ª resid.)",
    "financiacionMax": "80% (70% 2ª)",
    "diferencial": "Tramo fijo 5 años y medio al 2,34%/3,34%; resto Euríbor +0,74% (bonif.) / +1,74% (sin bonif.)",
    "vinculaciones": "Máx −1,00% (idéntico): nómina+Bizum/tarjeta −0,50%; hogar −0,20%; protección préstamos −0,30%; vida/otros −0,10%; ahorro ≥10.000€ −0,10%",
    "comisiones": "Apertura 0%; amortización 2% en tramo fijo, 0,25%/0,15% en tramo variable, máx pérdida financiera",
    "requisitos": "Importe mín. 20.000€; online. Variante \"Mixta Plus\" en oficina. Oferta hasta 15-jul-2026",
    "fuente": "Web oficial bancosantander.es + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "BBVA",
    "categoria": "Grande",
    "producto": "Fija BBVA",
    "tipo": "Fija",
    "tin": "2,95% / 3,95%",
    "tae": "4,04% / 4,60%",
    "plazoMax": "30 años (edad+plazo ≤75)",
    "financiacionMax": "80% habitual / 70% 2ª / 95% jóvenes <36",
    "diferencial": "",
    "vinculaciones": "Máx −1,00%: nómina ≥600€/pensión ≥300€/autónomo + seguro hogar BBVA Allianz (−0,50% conjunto); seguro amortización BBVA ≥50% del préstamo, máx 150.000€ (−0,50%)",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (después), máx pérdida financiera",
    "requisitos": "Residentes España, ingresos en euros; cuenta y seguro de daños obligatorios. Oferta hasta 31-jul-2026",
    "fuente": "Web oficial bbva.es + FIPRE 02-jun-2026 / Alta",
    "taeAnterior": "3,93% / 4,62%"
  },
  {
    "banco": "BBVA",
    "categoria": "Grande",
    "producto": "Variable BBVA",
    "tipo": "Variable",
    "tin": "Eur+0,60% / Eur+1,60%",
    "tae": "N/D",
    "plazoMax": "30 años (edad+plazo ≤75)",
    "financiacionMax": "80% habitual / 70% 2ª / 95% jóvenes <36",
    "diferencial": "Euríbor +0,60% (bonif.) / +1,60% (sin bonif.) desde año 2; revisión anual",
    "vinculaciones": "Máx −1,00%: nómina ≥600€/pensión ≥300€/autónomo + seguro hogar (−0,50% conjunto); seguro de amortización ≥50% (−0,50%)",
    "comisiones": "Apertura 0%; amortización 0,15% (5 primeros años)/0% (después)",
    "requisitos": "Cuenta y seguro daños obligatorios; sin cláusula suelo",
    "fuente": "Web oficial bbva.es + FIPRE 02-jun-2026 / Alta"
  },
  {
    "banco": "BBVA",
    "categoria": "Grande",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D",
    "financiacionMax": "N/D",
    "diferencial": "N/D",
    "vinculaciones": "N/D",
    "comisiones": "N/D",
    "requisitos": "BBVA NO comercializa hipoteca mixta como producto estándar (no figura en web ni FIPRE 02-jun-2026, solo fija y variable)",
    "fuente": "Web oficial bbva.es (ausencia) + comparador / Baja-Media"
  },
  {
    "banco": "CaixaBank",
    "categoria": "Grande",
    "producto": "Fija CasaFácil",
    "tipo": "Fija",
    "tin": "2,80% / 2,85%",
    "tae": "4,40% / 4,34%",
    "plazoMax": "30 años (plazo+edad ≤80)",
    "financiacionMax": "80% (vivienda habitual)",
    "diferencial": "",
    "vinculaciones": "Máx −1,00%: nómina ≥600€ + 3 recibos + compras tarjeta CaixaBank (−0,35%); seguro hogar (−0,15%); seguro vida ≥95% préstamo (−0,35%) o 50-95% (−0,20%) o solo salud (−0,20%); alarma Verisure (−0,15%)",
    "comisiones": "Apertura 0%, sin comisión de estudio; amortización 2% (10 primeros años)/1,5% (después), máx pérdida financiera",
    "requisitos": "Cuenta obligatoria 60€/año; tasación cliente ~289€; CaixaBank asume registro, notaría, gestoría y AJD",
    "fuente": "Web oficial caixabank.es (ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "CaixaBank",
    "categoria": "Grande",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D (hasta 30a vía asesor)",
    "financiacionMax": "80%",
    "diferencial": "N/D (comparadores citan Eur+0,50% con nómina)",
    "vinculaciones": "N/D",
    "comisiones": "N/D",
    "requisitos": "CaixaBank NO ofrece variable en catálogo público (solo CasaFácil fija y variante Eficiente); disponible vía estudio personalizado",
    "fuente": "Web oficial caixabank.es (ausencia) + comparadores / Baja-Media"
  },
  {
    "banco": "CaixaBank",
    "categoria": "Grande",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D",
    "financiacionMax": "80%",
    "diferencial": "N/D",
    "vinculaciones": "N/D",
    "comisiones": "N/D",
    "requisitos": "CaixaBank NO ofrece mixta en catálogo público; solo estudio personalizado",
    "fuente": "Web oficial caixabank.es (ausencia) + comparadores / Baja-Media"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Fija Bonificada",
    "tipo": "Fija",
    "tin": "2,75% / 3,75%",
    "tae": "3,58% / 4,32%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% 2ª)",
    "diferencial": "",
    "vinculaciones": "Hasta −1,00%: nómina + seguro hogar + seguro vida + protección de pagos (Sabadell no publica desglose por producto)",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (después), límite legal",
    "requisitos": "Web oficial no renderiza datos (JS); cifras vía comparadores",
    "fuente": "Comparador idealista/selectra, jul-2026 / Media"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Variable Bonificada",
    "tipo": "Variable",
    "tin": "Eur+0,50% / Eur+1,50%",
    "tae": "3,93%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% 2ª)",
    "diferencial": "Euríbor +0,50% (bonif.) / +1,50% (sin bonif.) desde año 2; revisión semestral",
    "vinculaciones": "Hasta −1,00%: nómina + seguro vida + seguro hogar (+ protección de pagos)",
    "comisiones": "Apertura 0%; amortización según límites legales (0,25%/0,15%)",
    "requisitos": "Revisión semestral (atípico); web no accesible vía fetch",
    "fuente": "Comparador idealista/selectra, jul-2026 / Media"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Mixta Bonificada",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 1,80% / 2,70%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% 2ª)",
    "diferencial": "Tramo fijo 3/5/7 años; después 3a Eur+0,70%/+1,60%; 5a +1,00%/+1,90%; 7a +1,30%/+2,20%",
    "vinculaciones": "Hasta −1,00%: nómina + seguro vida + seguro hogar",
    "comisiones": "Apertura 0%; amortización según límites legales por tramo",
    "requisitos": "Web no accesible vía fetch; cifras vía comparadores",
    "fuente": "Comparador idealista/selectra/kelisto, jul-2026 / Media"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "3,20% / 4,50%",
    "tae": "3,79% / 4,85%",
    "plazoMax": "30 años (ningún titular >75 al final)",
    "financiacionMax": "80% (60% 2ª)",
    "diferencial": "",
    "vinculaciones": "Máx −1,30%: cuenta Nómina/Profesional (−0,30%); seguro vida por total del préstamo (−0,60%); seguro hogar Generali (−0,30%); plan pensiones/EPSV ≥600€/año (−0,10%)",
    "comisiones": "Apertura N/D en ficha (500€ en variable/mixta); amortización según límites legales (2%/1,5% fija)",
    "requisitos": "Ingresos titulares >2.500€/mes; tasación ~284€. Oferta hasta agotar importe",
    "fuente": "Web oficial bankinter.com, jul-2026 / Alta-Media",
    "taeAnterior": "3,81% / 4,87%"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Nueva Hipoteca Variable",
    "tipo": "Variable",
    "tin": "Eur+0,50% / Eur+1,80%",
    "tae": "3,66% / 4,70%",
    "plazoMax": "30 años (titular ≤75 al final)",
    "financiacionMax": "80% (60% 2ª)",
    "diferencial": "Tramo fijo 3 años; después Euríbor +0,50% (bonif.) / +1,80% (sin bonif.), revisión anual",
    "vinculaciones": "Máx −1,30%: cuenta (−0,30%); seguro vida total (−0,60%); seguro hogar Generali (−0,30%); plan pensiones/EPSV ≥600€/año (−0,10%)",
    "comisiones": "Apertura 500€; amortización según límites legales; cuenta 45€/año",
    "requisitos": "Ingresos titulares >2.500€/mes; tasación 283,93€",
    "fuente": "Web oficial bankinter.com (ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,65% / 3,95%",
    "tae": "N/D",
    "plazoMax": "30 años (titular ≤75 al final)",
    "financiacionMax": "80% (60% 2ª)",
    "diferencial": "Tramo fijo 5/10/15 (hasta 20) años; después Euríbor +0,50% (bonif.) / +1,80% (sin bonif.)",
    "vinculaciones": "Máx −1,30%: cuenta (−0,30%); seguro vida total (−0,60%); seguro hogar Generali (−0,30%); plan pensiones/EPSV ≥600€/año (−0,10%)",
    "comisiones": "Apertura 500€; amortización según límites legales por tramo; cuenta 45€/año",
    "requisitos": "Ingresos titulares >2.500€/mes. Oferta hasta agotar 25M€",
    "fuente": "Web oficial bankinter.com, jul-2026 / Alta"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Mediano",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "3,10% / 4,10%",
    "tae": "4,09% / 4,24%",
    "plazoMax": "30 años (edad+plazo ≤75 1ª/≤70 2ª)",
    "financiacionMax": "80% 1ª / 70% 2ª",
    "diferencial": "",
    "vinculaciones": "Bonif. total máx −1,00 p.p. (desde 7º mes): nómina >600€ + tarjeta, seguro hogar, seguro vida (o desempleo/salud/auto), plan pensiones/fondos; desglose por producto N/D",
    "comisiones": "Apertura 0,15% (~225€); amortización 2% (10 primeros años)/1,5% (después), tope pérdida financiera",
    "requisitos": "Importe desde 50.000€, plazo desde 8 años; solo compra vivienda, residente España; cuenta + seguro daños oblig.",
    "fuente": "Web oficial unicajabanco.es (FIPRE/ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Mediano",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,55% / Eur+1,55%",
    "tae": "4,20% / 4,30%",
    "plazoMax": "30 años (edad+plazo ≤75/70)",
    "financiacionMax": "80% 1ª / 70% 2ª",
    "diferencial": "1er año fijo 1,90%; resto Euríbor +0,55% (bonif.) / +1,55% (sin bonif.); revisión anual",
    "vinculaciones": "Bonif. total máx −1,00 p.p. (desde 2º año): nómina >600€ + tarjeta (≥1.200€/12m), seguros hogar+vida (o alt.), pensiones/fondos; desglose N/D",
    "comisiones": "Apertura 0,15%; amortización 0,25% (3 primeros años, tope pérdida financiera), después 0%",
    "requisitos": "Importe desde 50.000€, plazo desde 8 años; cuenta + seguro daños oblig.",
    "fuente": "Web oficial unicajabanco.es (FIPRE/ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Mediano",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 3,00% / 4,00%",
    "tae": "4,18% / 4,38%",
    "plazoMax": "30 años (edad+plazo ≤75/70)",
    "financiacionMax": "80% 1ª / 70% 2ª",
    "diferencial": "10 años a tipo fijo; resto Euríbor +0,85% (bonif.) / +1,85% (sin bonif.); revisión semestral",
    "vinculaciones": "Bonif. total máx −1,00 p.p.: nómina >600€ + tarjeta, seguro hogar, seguro vida (o alt.), pensiones/fondos; desglose N/D",
    "comisiones": "Apertura 0,15%; amortización tramo fijo (10 años) máx 2%; tramo variable tope legal",
    "requisitos": "Importe desde 50.000€, plazo desde 8 años; cuenta + seguro daños oblig.",
    "fuente": "Web oficial unicajabanco.es (FIPRE/ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Mediano",
    "producto": "Joven (tipo fijo)",
    "tipo": "Fija",
    "tin": "3,25% / 4,25%",
    "tae": "4,24% / 4,39%",
    "plazoMax": "30 años (edad+plazo ≤75/70)",
    "financiacionMax": "80% 1ª / 70% 2ª; hasta 95-100% con avales autonómicos jóvenes",
    "diferencial": "",
    "vinculaciones": "Bonif. total máx −1,00 p.p.: nómina >600€ + tarjeta, seguros hogar/vida (o alt.), pensiones/fondos; desglose N/D",
    "comisiones": "Apertura 0,15%; amortización 2% (10 primeros años)/1,5% (después)",
    "requisitos": "Todos los titulares ≤35 años; solo compra vivienda",
    "fuente": "Web oficial unicajabanco.es (FIPRE/ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Mediano",
    "producto": "Joven (tipo variable)",
    "tipo": "Variable",
    "tin": "Eur+0,60% / Eur+1,60%",
    "tae": "4,28% / 4,38%",
    "plazoMax": "30 años (edad+plazo ≤75/70)",
    "financiacionMax": "80% 1ª / 70% 2ª; hasta 100% con avales autonómicos jóvenes",
    "diferencial": "1er año fijo 2,20%; resto Euríbor +0,60% (bonif.) / +1,60% (sin bonif.); revisión anual",
    "vinculaciones": "Bonif. total máx −1,00 p.p.: nómina >600€ + tarjeta (≥1.200€/12m), seguros hogar/vida (o alt.), pensiones/fondos; desglose N/D",
    "comisiones": "Apertura 0,15%; amortización 0,25% (3 primeros años), después 0%",
    "requisitos": "Todos los titulares ≤35 años; solo compra vivienda",
    "fuente": "Web oficial unicajabanco.es (FIPRE/ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Mediano",
    "producto": "Oxígeno (tipo fijo, vivienda eficiente)",
    "tipo": "Fija",
    "tin": "3,05% / 4,05%",
    "tae": "4,04% / 4,18%",
    "plazoMax": "30 años (edad+plazo ≤75/70)",
    "financiacionMax": "80% 1ª / 70% 2ª",
    "diferencial": "",
    "vinculaciones": "Bonif. total máx −1,00 p.p.: nómina >600€ + tarjeta, seguros hogar/vida (o alt.), pensiones/fondos; desglose N/D",
    "comisiones": "Apertura 0,15%; amortización 2% (10 primeros años)/1,5% (después)",
    "requisitos": "Solo vivienda con certificado energético A o B; importe desde 50.000€",
    "fuente": "Web oficial unicajabanco.es (FIPRE/ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Mediano",
    "producto": "Oxígeno (tipo variable, vivienda eficiente)",
    "tipo": "Variable",
    "tin": "Eur+0,55% / Eur+1,55%",
    "tae": "4,22% / 4,32%",
    "plazoMax": "30 años (edad+plazo ≤75/70)",
    "financiacionMax": "80% 1ª / 70% 2ª",
    "diferencial": "1er año fijo 2,10%; resto Euríbor +0,55% (bonif.) / +1,55% (sin bonif.); revisión anual",
    "vinculaciones": "Bonif. total máx −1,00 p.p.: nómina >600€ + tarjeta (≥1.200€/12m), seguros hogar/vida (o alt.), pensiones/fondos; desglose N/D",
    "comisiones": "Apertura 0,15%; amortización 0,25% (3 primeros años), después 0%",
    "requisitos": "Solo vivienda con certificado energético A o B",
    "fuente": "Web oficial unicajabanco.es (FIPRE/ej. repr.), jul-2026 / Alta"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Mediano",
    "producto": "Tipo Fijo",
    "tipo": "Fija",
    "tin": "3,50% / 4,50%",
    "tae": "3,99% / 4,72%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (menor entre tasación y compraventa)",
    "diferencial": "",
    "vinculaciones": "Reducción máx total −1 p.p. (desglose por producto N/D): nómina/pensión ≥3.000€/mes, seguro hogar, aportación EPSV/planes/fondos ≥2.400€/año, cert. energético A/B, tarjeta, seguro vida, protección pagos",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (después), solo con pérdida financiera",
    "requisitos": "Ingresos exigentes (~3.000€/mes para bonif. máx); Kutxabank asume notaría, gestoría, registro, IAJD; tasación cliente ~355€; tipos no publicados abiertamente",
    "fuente": "FIPRE oficial (may-2026) + comparadores, jul-2026 / Media"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Mediano",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,49% / Eur+1,49%",
    "tae": "3,67% / 4,30%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (menor entre tasación y compraventa)",
    "diferencial": "1er año fijo 1,96%; resto Euríbor +0,49% (bonif.) / +1,49% (sin bonif.); revisión anual",
    "vinculaciones": "Reducción máx total −1 p.p. (desglose N/D). Ej. para −1%: nómina ≥3.000€ + seguro hogar + aportación EPSV/planes/fondos ≥2.400€/año + cert. energético A/B",
    "comisiones": "Apertura 0%; amortización 0,25% (3 primeros años) o 0,15% (5 primeros), solo con pérdida financiera; después 0%",
    "requisitos": "Ej. 150.000€/30 años; tasación ~355€",
    "fuente": "Web oficial kutxabank.es + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Mediano",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,50% / 3,50%",
    "tae": "N/D",
    "plazoMax": "30 años (25 si 2ª vivienda)",
    "financiacionMax": "80% (70% 2ª residencia)",
    "diferencial": "Tramo fijo inicial 5/10/15 años; después Euríbor + diferencial (comparador +0,60%/+1,60%, valores oficiales N/D)",
    "vinculaciones": "Reducción máx total −1 p.p. (desglose N/D); mismo catálogo de vinculaciones que fija/variable",
    "comisiones": "Apertura 0% (confirmar); amortización tramo fijo 2%/1,5% y tramo variable 0,25%/0,15%, solo con pérdida financiera",
    "requisitos": "Edad máx 75 al finalizar (70 si 2ª); producto poco promocionado, exige simulador/oficina",
    "fuente": "FIPRE oficial confirma estructura + comparadores (ej.), jul-2026 / Media-Baja"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Mediano",
    "producto": "Joven (variable, <36 años)",
    "tipo": "Variable",
    "tin": "Eur+0,29% / Eur+0,39%",
    "tae": "3,63% / 4,26%",
    "plazoMax": "30 años",
    "financiacionMax": "Hasta 95% (jóvenes, según simulador; estándar 80%) — confirmar",
    "diferencial": "1er año fijo ~1,34%; resto Euríbor +0,29%/+0,39% (bonif.)",
    "vinculaciones": "Mismas vinculaciones + bonif. joven por edad (−0,10% TIN <35 años); individual N/D",
    "comisiones": "Apertura 0%; amortización como variable (0,25%/0,15%, solo con pérdida financiera)",
    "requisitos": "Para menores de 36 años; cifras de simulador (fluctúan con Euríbor)",
    "fuente": "Simulador oficial kutxabank.es + comparadores, jul-2026 / Media"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Mediano",
    "producto": "Vamos Fija",
    "tipo": "Fija",
    "tin": "2,55% / 3,55%",
    "tae": "3,49% / 3,80%",
    "plazoMax": "25 años",
    "financiacionMax": "80% (hasta 95% jóvenes ≤35)",
    "diferencial": "(tipo fijo; 1er año promocional 2,55%)",
    "vinculaciones": "Máx −1,00 p.p. con TODO el paquete (desglose individual N/D): nómina ≥2.500€/mes + ≥12 usos tarjeta/sem + ≥3 recibos + seguro hogar CASER + seguro vida + aportación ≥75€/mes a fondo",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (resto), tope pérdida financiera",
    "requisitos": "Importe mín. 100.000€; solo vivienda habitual; edad máx 75 al vencimiento; seguro daños oblig.",
    "fuente": "Web oficial ibercaja.es (ficha/ej. repr.), jul-2026 / Alta",
    "tinAnterior": "2,30% / 3,30%",
    "taeAnterior": "3,25% / 3,54%"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Mediano",
    "producto": "Vamos Variable",
    "tipo": "Variable",
    "tin": "Eur+0,60% / Eur+1,60%",
    "tae": "4,20% / 4,53%",
    "plazoMax": "25 años",
    "financiacionMax": "80%",
    "diferencial": "1er año fijo 2,00%; resto Euríbor +0,60% (bonif.) / +1,60% (sin bonif.); revisión semestral",
    "vinculaciones": "Máx −1,00 p.p. de diferencial (paquete completo; desglose N/D): nómina ≥2.500€ + ≥12 usos tarjeta/sem + ≥3 recibos + seguro hogar + seguro vida + aportación ≥75€/mes a fondo",
    "comisiones": "Apertura 0%; amortización tramo fijo (1er año) 2%; tramo variable 0,25% (3 primeros años) o 0,15% (5 primeros), tope pérdida financiera",
    "requisitos": "Importe mín. 100.000€; solo vivienda habitual; edad máx 75; seguro daños oblig.",
    "fuente": "Web oficial ibercaja.es, jul-2026 / Alta"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Mediano",
    "producto": "Mixta 5 Vamos",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 1,80% / 1,80%",
    "tae": "3,66% / 3,97%",
    "plazoMax": "25 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo 5 años (1,80% bonif./2,80% sin desde año 2); después Euríbor +0,60%/+1,60%; revisión semestral",
    "vinculaciones": "Máx −1,00 p.p. (paquete; desglose N/D): nómina ≥2.500€ + ≥12 usos tarjeta/sem + ≥3 recibos + seguro hogar + seguro vida + aportación ≥75€/mes a fondo",
    "comisiones": "Apertura 0%; amortización tramo fijo 2% (5 primeros años, tope pérdida financiera); tramo variable N/D",
    "requisitos": "Importe mín. 100.000€; solo vivienda habitual; edad máx 75",
    "fuente": "Web oficial ibercaja.es, jul-2026 / Alta",
    "taeAnterior": "3,69% / 4,00%"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Mediano",
    "producto": "Mixta 10 Vamos",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,10% / 2,10%",
    "tae": "3,45% / 3,76%",
    "plazoMax": "25 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo 10 años (2,10% bonif./3,10% sin desde año 2); después Euríbor +0,60%/+1,60%; revisión semestral",
    "vinculaciones": "Máx −1,00 p.p. (paquete; desglose N/D): nómina ≥2.500€ + ≥12 usos tarjeta/sem + ≥3 recibos + seguro hogar + seguro vida + aportación ≥75€/mes a fondo",
    "comisiones": "Apertura 0%; amortización tramo fijo 2% (10 primeros años, tope pérdida financiera)",
    "requisitos": "Importe mín. 100.000€; solo vivienda habitual; edad máx 75",
    "fuente": "Web oficial ibercaja.es, jul-2026 / Alta",
    "taeAnterior": "3,29% / 3,59%"
  },
  {
    "banco": "ABANCA",
    "categoria": "Mediano",
    "producto": "Fija Mari Carmen",
    "tipo": "Fija",
    "tin": "2,85% / 3,85%",
    "tae": "5,34% / 4,50%",
    "plazoMax": "30 años (plazo+edad ≤75)",
    "financiacionMax": "80% (menor tasación/compra; 60% 2ª según comparador)",
    "diferencial": "",
    "vinculaciones": "Máx −1,00%: nómina/ingreso 800-2.500€ o seg. sociales −0,20% (o ingreso ≥2.500€ −0,40%); seguro vida −0,30%; seguro hogar −0,20%; tarjeta (36 compras o 3.000€/año) −0,10%; plan pensiones −0,10%; fondos ≥100.000€ −0,10%; alarma −0,10%",
    "comisiones": "Apertura 0%; amortización 0%",
    "requisitos": "Ingresos mín. 2.300€/mes (1 titular) o 3.500€/mes (2); cuenta con comisión mantenimiento; TAE bonif. > sin bonif. por incluir coste seguros",
    "fuente": "Web oficial abanca.com + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "ABANCA",
    "categoria": "Mediano",
    "producto": "Variable Mari Carmen",
    "tipo": "Variable",
    "tin": "Eur+0,60% / Eur+1,60%",
    "tae": "5,31% / 4,66%",
    "plazoMax": "30 años (plazo+edad ≤75)",
    "financiacionMax": "80% (menor tasación/compra)",
    "diferencial": "1er año fijo; resto Euríbor 12m +0,60% (bonif.) / +1,60% (sin bonif.)",
    "vinculaciones": "Máx −1,00% (mismo menú): nómina/seg. sociales −0,20% (o ingreso ≥2.500€ −0,40%); vida −0,30%; hogar −0,20%; tarjeta −0,10%; pensiones −0,10%; fondos ≥100.000€ −0,10%; alarma −0,10%",
    "comisiones": "Apertura 0%; amortización 0%",
    "requisitos": "Ingresos mín. 2.300€/3.500€; cuenta manten. 36€/trim.; TAE bonif. > sin bonif.",
    "fuente": "Web oficial abanca.com + FIPRE, jul-2026 / Alta",
    "taeAnterior": "5,57% / 4,90%"
  },
  {
    "banco": "ABANCA",
    "categoria": "Mediano",
    "producto": "Mixta Mari Carmen",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,05% / 3,05%",
    "tae": "5,11% / 4,43%",
    "plazoMax": "30 años (plazo+edad ≤75)",
    "financiacionMax": "80% (menor tasación/compra)",
    "diferencial": "5 años a tipo fijo; resto Euríbor 12m +0,60% (bonif.) / +1,60% (sin bonif.)",
    "vinculaciones": "Máx −1,00% (mismo menú): nómina/seg. sociales −0,20% (varias vías −0,40%); vida −0,30%; hogar −0,20%; tarjeta −0,10%; pensiones −0,10%; fondos −0,10%; alarma −0,10%",
    "comisiones": "Apertura 0%; modificación 0%; amortización máx 2% (5 primeros años, solo con pérdida financiera)",
    "requisitos": "Ingresos mín. 2.300€/3.500€; cuenta manten. 40€/trim.",
    "fuente": "Web oficial abanca.com + FIPRE, jul-2026 / Alta",
    "taeAnterior": "5,16% / 4,48%"
  },
  {
    "banco": "ABANCA",
    "categoria": "Mediano",
    "producto": "Mari Carmen Vivienda Eficiente",
    "tipo": "Variable",
    "tin": "Eur+0,60% / Eur+1,60%",
    "tae": "5,56% / 4,88%",
    "plazoMax": "30 años (plazo+edad ≤75)",
    "financiacionMax": "80% (menor tasación/compra)",
    "diferencial": "1er año fijo; resto Euríbor 12m +0,60%/+1,60%; −0,10% adic. 1er año por cert. A/B",
    "vinculaciones": "Hasta −1,00% (mismo menú) + 0,10% extra 1er año por eficiencia A/B",
    "comisiones": "Apertura 0%; modificación 0%; amortización máx 0,15% (5 primeros años, solo con pérdida financiera)",
    "requisitos": "Solo viviendas cert. energético A o B; ingresos mín. 2.300€/3.500€",
    "fuente": "Web oficial abanca.com + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "ABANCA",
    "categoria": "Mediano",
    "producto": "Joven (Mi Primera Vivienda)",
    "tipo": "Fija/Variable",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "Hasta 40 años",
    "financiacionMax": "Hasta 100% (menor tasación/compra, según CCAA)",
    "diferencial": "Según modalidad elegida (Fija o Variable Mari Carmen)",
    "vinculaciones": "Bonificaciones de la Fija/Variable Mari Carmen (máx −1,00%); sin gastos notaría/registro/gestoría",
    "comisiones": "N/D",
    "requisitos": "Menor de 35 años, primera vivienda, convenio \"Mi Primera Vivienda\"; varias CCAA",
    "fuente": "Web oficial abanca.com (sin tipos publicados), jul-2026 / Media"
  },
  {
    "banco": "Banca March",
    "categoria": "Mediano",
    "producto": "Fija Avantio",
    "tipo": "Fija",
    "tin": "2,65% / 3,35%",
    "tae": "3,01% / 3,48%",
    "plazoMax": "30 años 1ª (20 años 2ª); mín. 10 años",
    "financiacionMax": "80% tasación 1ª / 70% 2ª",
    "diferencial": "Tipo fijo 2,65% toda la vida (sin bonif. sube a 3,35%)",
    "vinculaciones": "Máx acumulable −0,70% TIN: nómina/ingresos ≥2.000€/mes −0,20%; seguro vida −0,30%; seguro hogar −0,20%. Alt.: tarjeta ≥3.600€/año −0,20%, fondos ≥50.000€ −0,30%. Extra sostenibilidad −0,10%/−0,20%/−0,30% (una vez)",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (resto), tope pérdida financiera",
    "requisitos": "Importe mín. 200.000€ (nueva)/150.000€ (subrog.); ingresos netos familiares ≥4.000€/mes; online, <60 años; Cuenta Digital Avantio + seguro daños oblig.; banco asume aranceles notariales",
    "fuente": "Web oficial avantio.bancamarch.es + FIPRE (jun-2026), jul-2026 / Alta"
  },
  {
    "banco": "Banca March",
    "categoria": "Mediano",
    "producto": "Variable Avantio",
    "tipo": "Variable",
    "tin": "Eur+0,75% / Eur+1,45%",
    "tae": "3,86% / 4,34%",
    "plazoMax": "30 años 1ª (20 años 2ª); mín. 10 años",
    "financiacionMax": "80% tasación 1ª / 70% 2ª",
    "diferencial": "1er año fijo 2,75%; desde año 2 Euríbor 1 año +0,75% (bonif.) / +1,45% (sin bonif.); revisión anual",
    "vinculaciones": "Máx −0,70% sobre diferencial (desde 2º año): nómina ≥2.000€ −0,20%; seguro vida −0,30%; seguro hogar −0,20%",
    "comisiones": "Apertura 0%; amortización 0,15% (5 primeros años, tope pérdida financiera), 0% después; novación/subrog. a fijo 0,05% (3 primeros años)",
    "requisitos": "Importe mín. 200.000€ (nueva)/150.000€ (subrog.); ingresos ≥4.000€/mes. Web muestra texto antiguo; vinculante es FIPRE jun-2026",
    "fuente": "Web oficial avantio.bancamarch.es + FIPRE (jun-2026), jul-2026 / Alta"
  },
  {
    "banco": "Banca March",
    "categoria": "Mediano",
    "producto": "Mixta Avantio (Sostenible)",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,25% / 0,60%",
    "tae": "2,97% / 3,07%",
    "plazoMax": "30 años (fijo 10a; 2ª viv. 20 años); mín. 10 años",
    "financiacionMax": "80% tasación 1ª / 70% 2ª",
    "diferencial": "Tramo fijo 2,25% durante 10 años; desde año 11 Euríbor 1 año +0,60% a +1,30%; revisión anual",
    "vinculaciones": "Máx −0,70% sobre diferencial (desde año 11): nómina −0,20%; vida −0,30%; hogar −0,20%. Extra sostenibilidad −0,10%/−0,20%/−0,30% sobre tramo fijo",
    "comisiones": "Apertura 0%; amortización tramo fijo hasta 2% (tope pérdida financiera); novación/subrog. a fijo 0,05% (3 primeros años); tramo variable Ley 5/2019",
    "requisitos": "Importe mín. nueva 200.000-250.000€ (discrepante); subrog. 150.000€; ingresos ≥4.000€/mes",
    "fuente": "Web oficial avantio.bancamarch.es + FIPRE (abr-2026), jul-2026 / Alta",
    "taeAnterior": "2,73% / 2,82%"
  },
  {
    "banco": "Banco Mediolanum",
    "categoria": "Mediano",
    "producto": "Fija (tipo fijo puro)",
    "tipo": "Fija",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D",
    "financiacionMax": "N/D",
    "diferencial": "N/D",
    "vinculaciones": "N/D",
    "comisiones": "N/D",
    "requisitos": "Banco Mediolanum NO ofrece hipoteca a tipo fijo puro; solo variable y mixta (ambas con 1er año a tipo fijo)",
    "fuente": "Web oficial bancomediolanum.es + comparadores, jul-2026 / Alta"
  },
  {
    "banco": "Banco Mediolanum",
    "categoria": "Mediano",
    "producto": "Freedom (Variable)",
    "tipo": "Variable",
    "tin": "Eur+0,65% / Eur+1,35%",
    "tae": "3,70% / 4,50%",
    "plazoMax": "30 años (o hasta 80 años de edad)",
    "financiacionMax": "80% (menor compra/tasación)",
    "diferencial": "1er año fijo 1,50%; desde año 2 Euríbor 12m +0,65% (bonif.) / +1,35% (sin bonif.); revisión trimestral",
    "vinculaciones": "Máx −0,70% TIN: nómina ≥3.000€/mes −0,55% (o 1.200-2.999€ −0,40%); seguro vida Generali −0,15%",
    "comisiones": "Apertura 1%; amortización parcial/total 0,15% (5 primeros años)/0% resto",
    "requisitos": "Cuenta corriente oblig. (gratuita); seguro daños oblig.; banco asume notaría/registro/gestoría; tasación ~350€ cliente; importe mín. N/D",
    "fuente": "roams + hipotify + PDF oficial (estructura), jul-2026 / Media-Alta",
    "taeAnterior": "3,51% / 4,06%"
  },
  {
    "banco": "Banco Mediolanum",
    "categoria": "Mediano",
    "producto": "Freedom Green (Variable)",
    "tipo": "Variable",
    "tin": "Eur+0,50% / Eur+0,75%",
    "tae": "3,60% / 3,90%",
    "plazoMax": "30 años (o hasta 80 años de edad)",
    "financiacionMax": "80% (menor compra/tasación)",
    "diferencial": "1er año fijo 1,50%; desde año 2 Euríbor 12m +0,50% (bonif.) / +0,75% (sin bonif.); revisión trimestral",
    "vinculaciones": "Máx −0,25% TIN: nómina ≥1.200€/mes −0,10%; seguro vida Generali −0,15%",
    "comisiones": "Apertura 1%; amortización parcial/total 0,15% (5 primeros años)/0% resto",
    "requisitos": "Solo 1ª vivienda con cert. energético B o superior; cuenta corriente oblig.; banco asume notaría/registro/gestoría; importe mín. N/D",
    "fuente": "roams + hipotify + comparativadebancos, jul-2026 / Media-Alta"
  },
  {
    "banco": "Banco Mediolanum",
    "categoria": "Mediano",
    "producto": "Freedom Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 1,99% / 2,50%",
    "tae": "3,59% / 4,33%",
    "plazoMax": "30 años (o hasta 80 años de edad)",
    "financiacionMax": "80% (menor compra/tasación)",
    "diferencial": "Tramo fijo 5 años (año 1 1,99%; años 2-5 2,50% bonif./3,20% sin); desde año 6 Euríbor 12m +0,79% (bonif.) / +1,49% (sin bonif.); revisión trimestral",
    "vinculaciones": "Máx −0,70% TIN: nómina ≥3.000€/mes −0,55% (o 1.200-2.999€ −0,40%); seguro vida Generali −0,15%",
    "comisiones": "Apertura 1%; amortización N/D (consultar FEIN)",
    "requisitos": "Cuenta corriente oblig.; seguro daños oblig.; banco asume notaría/registro/gestoría; importe mín. N/D",
    "fuente": "comparativadebancos + roams + PDF oficial, jul-2026 / Media-Alta",
    "taeAnterior": "3,56% / 4,11%"
  },
  {
    "banco": "Banco Mediolanum",
    "categoria": "Mediano",
    "producto": "Freedom Green Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 1,99% / 2,50%",
    "tae": "3,50% / 3,84%",
    "plazoMax": "30 años (o hasta 80 años de edad)",
    "financiacionMax": "80% (menor compra/tasación)",
    "diferencial": "Tramo fijo 5 años (año 1 1,99%; años 2-5 2,50% bonif./2,75% sin); desde año 6 Euríbor 12m +0,69% (bonif.) / +0,94% (sin bonif.); revisión trimestral",
    "vinculaciones": "Máx −0,25% TIN: nómina ≥1.200€/mes −0,10%; seguro vida Generali −0,15%",
    "comisiones": "Apertura 1%; amortización N/D (consultar FEIN)",
    "requisitos": "Solo 1ª vivienda con cert. energético B o superior; cuenta corriente oblig.; banco asume notaría/registro/gestoría",
    "fuente": "comparativadebancos + roams, jul-2026 / Media-Alta"
  },
  {
    "banco": "Cajamar",
    "categoria": "Mediano",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,30% / 3,10%",
    "tae": "N/D",
    "plazoMax": "30 años (mín. 25; venc. antes de que el titular más joven cumpla 80)",
    "financiacionMax": "80% (menor tasación/compra; solo vivienda habitual)",
    "diferencial": "Tramo fijo 5 años; resto Euríbor +0,60% (bonif.) / +1,40% (sin bonif.)",
    "vinculaciones": "Máx −0,80% (exige ser socio, aportación 61€): seguro vida riesgo −0,30%; nómina+banca electrónica+3 recibos (>700€) −0,20%; seguro hogar −0,10%; tarjetas (≥3.000€/año o 10 op.) −0,10%; saldo medio ≥15.000€ o ≥10.000€ fondos −0,10%",
    "comisiones": "Apertura 0%; amortización 0,25% (años 1-3)/0,15% (años 4-5), tope pérdida financiera; novación ampliación plazo máx 0,10%",
    "requisitos": "Importe ≥60.000€; ingresos unidad familiar ≥4.000€/mes; endeudamiento ≤35%",
    "fuente": "Web oficial cajamar.es (producto + condiciones legales), jul-2026 / Alta"
  },
  {
    "banco": "Cajamar",
    "categoria": "Mediano",
    "producto": "Mixta Soystenible (vivienda CEE A/B)",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "30 años (mín. 25)",
    "financiacionMax": "80% (vivienda habitual)",
    "diferencial": "Igual estructura que Mixta (5 años fijo + Euríbor) con mejora por eficiencia A/B (cuantía N/D)",
    "vinculaciones": "Mismas bonificaciones que la Mixta (máx −0,80%)",
    "comisiones": "Apertura 0%; amortización igual que Mixta (0,25%/0,15%)",
    "requisitos": "Mismos requisitos que la Mixta; requiere Certificado Eficiencia Energética A o B",
    "fuente": "Web oficial cajamar.es (tipos concretos no publicados), jul-2026 / Alta"
  },
  {
    "banco": "Cajamar",
    "categoria": "Mediano",
    "producto": "HipotecON Fija (legacy, fuera de catálogo actual)",
    "tipo": "Fija",
    "tin": "2,75% / 2,85%",
    "tae": "3,44% / 3,54%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (menor tasación/compra; vivienda habitual)",
    "diferencial": "",
    "vinculaciones": "Ser socio (61€) + seguros vida/hogar, nómina y vinculación; % por producto N/D",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (después)",
    "requisitos": "Ingresos ≥4.000€/mes; importe ≥60.000€; endeudamiento ≤30-35%",
    "fuente": "Comparadores Kelisto/iAhorro (jun-jul 2026); NO en cajamar.es (posible descatalogado), jul-2026 / Media",
    "tinAnterior": "2,60% / 3,20%",
    "taeAnterior": "3,39% / 3,38%"
  },
  {
    "banco": "Cajamar",
    "categoria": "Mediano",
    "producto": "HipotecON Variable (legacy, fuera de catálogo actual)",
    "tipo": "Variable",
    "tin": "Eur+0,50%",
    "tae": "2,86%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (vivienda habitual)",
    "diferencial": "Diferencial Euríbor +0,50% (bonif.); 1er año a tipo fijo",
    "vinculaciones": "Ser socio (61€) + nómina/seguros/vinculación; % por producto N/D",
    "comisiones": "Apertura 0%; amortización 0,25% (años 1-3)/0,15% (años 4-5), 0% después",
    "requisitos": "Ingresos ≥4.000€/mes; importe ≥60.000€",
    "fuente": "Comparadores Kelisto/iAhorro (jun-jul 2026); NO en cajamar.es, cifras posiblemente desactualizadas, jul-2026 / Baja"
  },
  {
    "banco": "Caja de Ingenieros",
    "categoria": "Mediano",
    "producto": "Fija 15",
    "tipo": "Fija",
    "tin": "2,60% / 3,60%",
    "tae": "3,467% / 4,273%",
    "plazoMax": "15 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Máx −1,00% en tipo (y −0,75% en apertura): nómina+3 recibos+tarjeta crédito −0,25%; seguro protección de pagos (prima única 5 años) −0,15%; seguro vida −0,40%; seguro Multirriesgo Hogar −0,20%",
    "comisiones": "Apertura 0% (bonif. máx)/0,75% (sin bonif.); amortización 2,00% (10 primeros años)/1,50% (resto), solo con pérdida financiera",
    "requisitos": "Ser socio cooperativo (100€ reembolsable) + cuenta CI; vivienda habitual; sin gastos notaría/gestoría/registro, CI asume IAJD (salvo País Vasco); tasación cliente ~266€",
    "fuente": "Web oficial caixaenginyers.com + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "Caja de Ingenieros",
    "categoria": "Mediano",
    "producto": "Fija 20",
    "tipo": "Fija",
    "tin": "2,65% / 3,65%",
    "tae": "3,450% / 4,271%",
    "plazoMax": "20 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Máx −1,00% en tipo (y −0,75% en apertura): nómina+3 recibos+tarjeta crédito −0,25%; seguro protección de pagos −0,15%; seguro vida −0,40%; seguro Multirriesgo Hogar −0,20%",
    "comisiones": "Apertura 0% (bonif. máx)/0,75% (sin bonif.); amortización 2,00% (10 primeros años)/1,50% (resto), solo con pérdida financiera",
    "requisitos": "Ser socio cooperativo (100€ reembolsable) + cuenta CI; vivienda habitual; sin gastos notaría/gestoría/registro, CI asume IAJD (salvo País Vasco)",
    "fuente": "Web oficial caixaenginyers.com + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "Caja de Ingenieros",
    "categoria": "Mediano",
    "producto": "Fija 30",
    "tipo": "Fija",
    "tin": "2,70% / 3,70%",
    "tae": "3,451% / 4,283%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Máx −1,00% en tipo (y −0,75% en apertura): nómina+3 recibos+tarjeta crédito −0,25%; seguro protección de pagos −0,15%; seguro vida −0,40%; seguro Multirriesgo Hogar −0,20%",
    "comisiones": "Apertura 0% (bonif. máx)/0,75% (sin bonif.); amortización 2,00% (10 primeros años)/1,50% (resto), solo con pérdida financiera",
    "requisitos": "Ser socio cooperativo (100€ reembolsable) + cuenta CI; vivienda habitual; sin gastos notaría/gestoría/registro, CI asume IAJD (salvo País Vasco)",
    "fuente": "Web oficial caixaenginyers.com + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "Caja de Ingenieros",
    "categoria": "Mediano",
    "producto": "Hogar (Variable)",
    "tipo": "Variable",
    "tin": "Eur+0,65% / Eur+1,65%",
    "tae": "4,050% / 4,887%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "1er año a tipo fijo; resto Euríbor +0,65% (bonif. tramo 80%)/+1,65% (sin); revisión anual",
    "vinculaciones": "Máx −1,00% en tipo (y −0,75% en apertura): nómina+3 recibos+tarjeta crédito −0,25%; seguro protección de pagos −0,15%; seguro vida −0,40%; seguro Multirriesgo Hogar −0,20%",
    "comisiones": "Apertura 0% (bonif. máx)/0,75% (sin bonif.); amortización 0,15% (5 primeros años), 0% después, solo con pérdida financiera",
    "requisitos": "Ser socio cooperativo (100€ reembolsable) + cuenta CI; vivienda habitual; CI asume IAJD (salvo País Vasco)",
    "fuente": "Web oficial caixaenginyers.com + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "Caja de Ingenieros",
    "categoria": "Mediano",
    "producto": "Mixta 5",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,60% / 3,60%",
    "tae": "3,856% / 4,687%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Fijo los 5 primeros años; resto Euríbor +0,65% (bonif.)/+1,65% (sin); revisión anual",
    "vinculaciones": "Máx −1,00% en tipo (y −0,75% en apertura): nómina+3 recibos+tarjeta crédito −0,25%; seguro protección de pagos −0,15%; seguro vida −0,40%; seguro Multirriesgo Hogar −0,20%",
    "comisiones": "Apertura 0% (bonif. máx)/0,75% (sin bonif.); amortización 2,00% (5 primeros años), solo con pérdida financiera",
    "requisitos": "Ser socio cooperativo (100€ reembolsable) + cuenta CI; vivienda habitual; solo publicado tramo 80%",
    "fuente": "Web oficial caixaenginyers.com + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "Caja de Ingenieros",
    "categoria": "Mediano",
    "producto": "Mixta 10",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,70% / 3,70%",
    "tae": "3,686% / 4,514%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Fijo los 10 primeros años; resto Euríbor +0,65% (bonif.)/+1,65% (sin); revisión anual",
    "vinculaciones": "Máx −1,00% en tipo (y −0,75% en apertura): nómina+3 recibos+tarjeta crédito −0,25%; seguro protección de pagos −0,15%; seguro vida −0,40%; seguro Multirriesgo Hogar −0,20%",
    "comisiones": "Apertura 0% (bonif. máx)/0,75% (sin bonif.); amortización 2,00% (10 primeros años), solo con pérdida financiera",
    "requisitos": "Ser socio cooperativo (100€ reembolsable) + cuenta CI; vivienda habitual; solo publicado tramo 80%",
    "fuente": "Web oficial caixaenginyers.com + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "NARANJA Fija",
    "tipo": "Fija",
    "tin": "3,85% / 4,35%",
    "tae": "4,58% / 4,46%",
    "plazoMax": "25 años (30 si <36 años y >80%)",
    "financiacionMax": "80% tasación (90% s/compra; hasta 100% jóvenes <36 y vivienda ≤400.000€)",
    "diferencial": "",
    "vinculaciones": "Nómina o ingreso ≥600€/mes o saldo ≥2.000€ + seguro hogar + seguro vida (rebaja efectiva ≈0,50% TIN; TAE bonif. sale mayor por el coste de los seguros)",
    "comisiones": "Apertura 0%; amortización parcial/total 2% (10 primeros años) y 1,5% después (solo si pérdida financiera)",
    "requisitos": "Importe mín. 50.000€; ING paga notaría/gestoría/registro e IAJD salvo tasación; ej. 150.000€/25 años",
    "fuente": "Web oficial ing.es + FIPRE vía idealista, jul-2026 / Alta"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "NARANJA Variable",
    "tipo": "Variable",
    "tin": "Eur+0,85% / Eur+1,35%",
    "tae": "4,24% / 4,11%",
    "plazoMax": "40 años (mín. 9)",
    "financiacionMax": "80% tasación (90% s/compra)",
    "diferencial": "Euríbor +0,85% (bonif.) / +1,35% (sin bonif.); 1 o 3 años iniciales a tipo fijo",
    "vinculaciones": "Nómina/ingreso ≥600€ o saldo ≥2.000€ + hogar + vida (≈0,50% en el diferencial)",
    "comisiones": "Apertura 0%; amortización parcial 0%; amort. total tramo variable 0,15% (5 primeros años, solo si pérdida)",
    "requisitos": "Revisión semestral; euríbor jun-2026 2,804%",
    "fuente": "Web oficial ing.es + FIPRE vía idealista, jul-2026 / Alta"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "NARANJA Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,40% / 2,90%",
    "tae": "3,75% / 3,61%",
    "plazoMax": "40 años",
    "financiacionMax": "80% tasación (90% s/compra)",
    "diferencial": "Tramo fijo 5/10/15/20 años; tras el fijo Euríbor +0,89% (bonif.) / +1,39% (sin bonif.) para tramo de 5 años",
    "vinculaciones": "Nómina/ingreso ≥600€ o saldo ≥2.000€ + hogar + vida; cert. energético A/B: −0,10% TIN",
    "comisiones": "Apertura 0%; cambio condiciones 0%; amort. parcial 0%; amort. total tramo fijo 2%/1,5% y tramo variable 0,15% (solo si pérdida)",
    "requisitos": "TIN y diferencial suben cuanto más largo el tramo fijo",
    "fuente": "Web oficial ing.es + FIPRE vía idealista, jul-2026 / Alta",
    "taeAnterior": "3,96% / 3,83%"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Open Fija",
    "tipo": "Fija",
    "tin": "2,80% / 3,30%",
    "tae": "3,41% / 3,60%",
    "plazoMax": "30 años (edad+plazo ≤80)",
    "financiacionMax": "80% (1ª) / 70% (2ª)",
    "diferencial": "; si financias >150.000€ −0,10% adicional",
    "vinculaciones": "Nómina/pensión ≥900€ (1 titular) o ≥1.800€ (2) = −0,30%; seguro hogar Zurich = −0,10%; seguro vida Zurich = −0,10% (total −0,50%)",
    "comisiones": "Apertura 0%; parcial/subrogación/cambio 0%; amort. total 2% (10 primeros años) y 1,5% resto (límite pérdida)",
    "requisitos": "Importe 30.000-3.000.000€; seguro daños obligatorio (libre elección); sin abrir cuenta hasta la firma",
    "fuente": "Web oficial openbank.es, jul-2026 / Alta"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Open Variable",
    "tipo": "Variable",
    "tin": "Eur+0,65% / Eur+1,15%",
    "tae": "3,88% / 4,11%",
    "plazoMax": "30 años (edad+plazo ≤80)",
    "financiacionMax": "80% (1ª) / 70% (2ª)",
    "diferencial": "Euríbor +0,65% (bonif.) / +1,15% (sin bonif.); 1er año fijo",
    "vinculaciones": "Ingresos ≥900€/1.800€ (−0,30%) + hogar (−0,10%) + vida (−0,10%) = −0,50%",
    "comisiones": "Apertura 0%; parcial/subrogación/cambio 0%; amort. total limitada a pérdida financiera (% exacto N/D)",
    "requisitos": "Euríbor jun-2026 2,804%; revisión anual",
    "fuente": "Web oficial openbank.es + nota prensa, jul-2026 / Media-Alta"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Open Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,80% / 3,30%",
    "tae": "3,72% / 3,94%",
    "plazoMax": "30 años (edad+plazo ≤80)",
    "financiacionMax": "80% (1ª) / 70% (2ª)",
    "diferencial": "Tramo fijo 5 años; después Euríbor +0,60% (bonif.) / +1,10% (sin bonif.)",
    "vinculaciones": "Ingresos ≥900€/1.800€ (−0,30%) + hogar (−0,10%) + vida (−0,10%) = −0,50%; si >150.000€ −0,10%",
    "comisiones": "Apertura 0%; parcial/subrogación/cambio 0%; amort. total 2% (5 primeros años) y 0% resto (límite pérdida)",
    "requisitos": "Euríbor jun-2026 2,804%; revisión anual tras el año 5",
    "fuente": "Web oficial openbank.es, jul-2026 / Alta"
  },
  {
    "banco": "MyInvestor",
    "categoria": "Online",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "3,40% / 3,40%",
    "tae": "3,61% / 3,61%",
    "plazoMax": "30 años (mín. 8)",
    "financiacionMax": "80% (1ª) / 70% (2ª) / 60% no residentes",
    "diferencial": "",
    "vinculaciones": "SIN vinculaciones ni productos obligatorios (no exige nómina ni seguros); seguro de daños obligatorio por ley pero de libre elección",
    "comisiones": "Apertura 0% (compra vivienda hasta 80%/70%); 1% en otros fines; amort. parcial solo si >25% capital/año; amort. total fija 2% (10a)/1,5%",
    "requisitos": "Ingresos mín. 4.000€/mes netos conjuntos (3.000€ funcionarios); importe mín. 100.000€; asume tasación/notaría/gestoría/registro",
    "fuente": "Web oficial myinvestor.es + FIPRE, jul-2026 / Alta"
  },
  {
    "banco": "MyInvestor",
    "categoria": "Online",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,69% / Eur+0,79%",
    "tae": "N/D",
    "plazoMax": "30 años (mín. 8)",
    "financiacionMax": "80% / 70% / 60% no residentes",
    "diferencial": "Euríbor +0,69% (con productos \"A Tu Manera\") / +0,79% (sin productos); 1er año a tipo fijo",
    "vinculaciones": "Sin vinculación obligatoria; contratar seguros/inversión (\"A Tu Manera\") baja el diferencial hasta 0,20 p.p. (opcional)",
    "comisiones": "Apertura 0% (compra); amort. parcial solo si >25%/año; amort. total variable máx 0,25% (3 primeros años) y 0% después",
    "requisitos": "Ingresos mín. 4.000€/mes; importe mín. 100.000€; MyInvestor NO comercializa hipoteca mixta",
    "fuente": "Web oficial myinvestor.es + nota prensa, jul-2026 / Media-Alta"
  },
  {
    "banco": "imagin",
    "categoria": "Online",
    "producto": "Fija imaginBank",
    "tipo": "Fija",
    "tin": "3,05% / 3,80%",
    "tae": "3,774% / 4,288%",
    "plazoMax": "30 años (edad titular ≤80 al vencimiento)",
    "financiacionMax": "Hasta 90% jóvenes <36 (vía programas CCAA/ICO); estándar 80%",
    "diferencial": "",
    "vinculaciones": "Nómina/pensión ≥1.200€ (−0,30 p.p.) + seguro vida VidaCaixa por 50% capital (−0,30 p.p.) + seguro hogar SegurCaixa (−0,15 p.p.) = −0,75 p.p.",
    "comisiones": "Apertura 0%; amort. total/parcial 2% (10 primeros años) y 1,5% resto (límite pérdida)",
    "requisitos": "Préstamo emitido por CaixaBank; cuenta imagin gratis; seguro daños obligatorio (libre); oferta válida hasta 21-jul-2026; orientada a jóvenes",
    "fuente": "Web oficial imagin.com + FEIN, jul-2026 / Alta"
  },
  {
    "banco": "imagin",
    "categoria": "Online",
    "producto": "Mixta imaginBank",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,95% / 3,70%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "Hasta 90% jóvenes / 80% estándar",
    "diferencial": "Tramo fijo 5 años; después Euríbor +0,85% (bonif.) / +1,60% (sin bonif.)",
    "vinculaciones": "Nómina/pensión ≥1.200€ (+ seguros hogar y vida)",
    "comisiones": "Apertura 0%; amort. total/parcial con límite de pérdida financiera",
    "requisitos": "Emitida por CaixaBank; principalmente para jóvenes",
    "fuente": "Comparador HelpMyCash/Kelisto, jul-2026 / Media"
  },
  {
    "banco": "Pibank",
    "categoria": "Online",
    "producto": "Pibank Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 1,99% / 1,99%",
    "tae": "3,30%",
    "plazoMax": "35 años (mín. 15)",
    "financiacionMax": "80% tasación / 90% compra (compraventa >100.000€)",
    "diferencial": "Tramo fijo 4 años (48 cuotas) al 1,99%; después Euríbor +0,68%",
    "vinculaciones": "Solo cuenta Pibank + seguro de daños (libre elección); NO exige nómina; sin bonificaciones por productos",
    "comisiones": "Apertura 0%; estudio 0%; amort. anticipada total y parcial 0%",
    "requisitos": "Importe 80.000-2.000.000€; residente España, contrato indefinido/funcionario, 21-75 años; Pibank asume tasación/notaría/gestoría/registro; único producto hipotecario",
    "fuente": "Web oficial pibank.es, jul-2026 / Alta",
    "taeAnterior": "3,22% / 3,24%"
  },
  {
    "banco": "Targobank",
    "categoria": "Otro",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,65% / Eur+1,65%",
    "tae": "3,1%",
    "plazoMax": "N/D (típico 30a)",
    "financiacionMax": "80% tasación (1ª) / 60% (2ª)",
    "diferencial": "Euríbor +0,65% (bonif.) / +1,65% (sin bonif.); 1er año fijo ~2,85%",
    "vinculaciones": "Nómina ≥2.000€ (~0,10-0,25 p.p.) + seguro vida 100% (0,50 p.p.) + seguro hogar (0,25 p.p.) + 3 recibos y ≥6 compras tarjeta/trim. (0,15 p.p.) = hasta ~1,00 p.p.",
    "comisiones": "Apertura 0%; gestoría/registro/notaría a cargo del banco; amort. N/D",
    "requisitos": "Targobank no publica tarifas claras; requiere oferta personalizada",
    "fuente": "Comparador roams/kelisto/helpmycash, jul-2026 / Media"
  },
  {
    "banco": "Targobank",
    "categoria": "Otro",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D",
    "financiacionMax": "80% tasación",
    "diferencial": "",
    "vinculaciones": "Nómina ≥2.000€ + seguros vida/hogar + recibos/tarjeta",
    "comisiones": "Apertura 0%",
    "requisitos": "Tipo fijo actual no disponible en fuentes fiables; solicitar oferta personalizada",
    "fuente": "Comparador (dato obsoleto), jul-2026 / Baja"
  },
  {
    "banco": "Targobank",
    "categoria": "Otro",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 3,00% / 0,90%",
    "tae": "N/D",
    "plazoMax": "N/D",
    "financiacionMax": "80% tasación",
    "diferencial": "Tramo fijo 5 años al 3,00%; después Euríbor +0,90%",
    "vinculaciones": "Nómina ≥2.000€ + seguros vida/hogar + recibos/tarjeta",
    "comisiones": "Apertura 0%; gestoría/registro/notaría a cargo del banco",
    "requisitos": "TAE no publicada; requiere oferta personalizada",
    "fuente": "Comparador hipotecas.me/roams, jul-2026 / Media"
  },
  {
    "banco": "Deutsche Bank España",
    "categoria": "Otro",
    "producto": "Variable DB",
    "tipo": "Variable",
    "tin": "Eur+0,70%",
    "tae": "4,25%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (menor entre compra y tasación), vivienda habitual",
    "diferencial": "Euríbor +0,70% (comparador); 1er año a tipo fijo",
    "vinculaciones": "Nómina + seguros (hogar/vida/protección pagos); importe bonificación N/D",
    "comisiones": "Apertura N/D (comparador 0%); amort. anticipada 0,15% (5 primeros años) y 0% después (solo si pérdida)",
    "requisitos": "DB NO publica TIN/TAE en su web (requiere gestor); estructura y comisiones sí confirmadas en web oficial",
    "fuente": "Web oficial (estructura) + comparador (tipos), jul-2026 / Media",
    "taeAnterior": "3,73% / 5,09%"
  },
  {
    "banco": "Deutsche Bank España",
    "categoria": "Otro",
    "producto": "Mixta DB",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,75% / 0,70%",
    "tae": "4,50%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (menor entre compra y tasación)",
    "diferencial": "Tramo fijo ~5 años; después Euríbor +0,70% (comparador)",
    "vinculaciones": "Nómina + seguros; importe bonificación N/D",
    "comisiones": "Apertura N/D; amort. anticipada en periodo fijo 2% (límite pérdida) y 0% resto",
    "requisitos": "Permite reducir cuota o plazo; DB no publica tipos en web",
    "fuente": "Web oficial (estructura) + comparador (tipos), jul-2026 / Media",
    "taeAnterior": "3,47% / 4,88%"
  },
  {
    "banco": "Deutsche Bank España",
    "categoria": "Otro",
    "producto": "Sostenible DB (vivienda eficiente)",
    "tipo": "Fija",
    "tin": "3,30%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "(fija; también variante mixta)",
    "vinculaciones": "Nómina + seguros; dirigida a viviendas con alta calificación energética",
    "comisiones": "Apertura N/D; amort. según Ley 5/2019",
    "requisitos": "Producto para vivienda eficiente; DB no publica tipos oficialmente",
    "fuente": "Web oficial (existencia) + comparador (tipos), jul-2026 / Media-Baja"
  },
  {
    "banco": "EVO Banco",
    "categoria": "Online",
    "producto": "Inteligente Fija (histórica)",
    "tipo": "Fija",
    "tin": "2,70% / 3,10%",
    "tae": "3,18% / 3,37%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina ≥600€ + seguro hogar + seguro vida",
    "comisiones": "Apertura 0%; amort. según Ley 5/2019",
    "requisitos": "MARCA INTEGRADA EN BANKINTER (~jul-2025); no se confirma comercialización activa de nuevas hipotecas; cifras heredadas",
    "fuente": "Comparador kelisto/rankia, jul-2026 / Baja"
  },
  {
    "banco": "EVO Banco",
    "categoria": "Online",
    "producto": "Inteligente Variable (histórica)",
    "tipo": "Variable",
    "tin": "Eur+0,48% / Eur+0,88%",
    "tae": "3,42% / 3,61%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Euríbor +0,48% (bonif.) / +0,88% (sin bonif.); 2 años iniciales fijos",
    "vinculaciones": "Nómina ≥600€ + seguro hogar + seguro vida",
    "comisiones": "Apertura 0%; amort. según Ley 5/2019",
    "requisitos": "Marca integrada en Bankinter; no confirmada como activa",
    "fuente": "Comparador, jul-2026 / Baja"
  },
  {
    "banco": "EVO Banco",
    "categoria": "Online",
    "producto": "Inteligente Mixta (histórica)",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,35% / 2,55%",
    "tae": "3,27% / 3,46%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo 3 o 5 años; después Euríbor +0,60% (bonif.) / +0,80% (sin bonif.)",
    "vinculaciones": "Nómina ≥600€ + seguro hogar + seguro vida",
    "comisiones": "Apertura 0%; amort. según Ley 5/2019",
    "requisitos": "Marca integrada en Bankinter",
    "fuente": "Comparador, jul-2026 / Baja"
  },
  {
    "banco": "Caja Rural de Navarra",
    "categoria": "Cooperativa",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "2,55% / 3,55%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina/pensión + seguro hogar + seguro vida + tarjeta; desglose % no publicado (ref. hist. FIPRE 2021: nómina −0,25%, tarjeta −0,15%, hogar −0,10%, vida −0,25%)",
    "comisiones": "Apertura: sin comisión (comparador); amortización 2% (10 primeros años)/1,5% (después)",
    "requisitos": "Zona Navarra/País Vasco/La Rioja; web no publica TIN/TAE (remite a simulador/oficina)",
    "fuente": "Web oficial (sin tipos) + comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Caja Rural de Navarra",
    "categoria": "Cooperativa",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,65% / Eur+1,15%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Euríbor +0,65% (bonif.) / +1,15% (sin bonif.); sin tramo fijo inicial",
    "vinculaciones": "Nómina/pensión + seguro hogar + seguro vida + tarjeta; desglose % no publicado",
    "comisiones": "Apertura: sin comisión; amortización 2% (10 primeros años)/1,5% (después)",
    "requisitos": "Zona Navarra/País Vasco/La Rioja; web no publica diferencial (remite a simulador/oficina)",
    "fuente": "Web oficial (sin tipos) + comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Caja Rural de Navarra",
    "categoria": "Cooperativa",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,45% / 3,55%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo 5 años al 2,45% TIN; después Euríbor +0,75% (bonif.) / +1,25% (sin bonif.)",
    "vinculaciones": "Nómina/pensión + seguro hogar + seguro vida + tarjeta; desglose % no publicado",
    "comisiones": "Apertura: sin comisión; amortización 2% (10 primeros años)/1,5% (después)",
    "requisitos": "Zona Navarra/País Vasco/La Rioja; web no publica tipos (remite a simulador/oficina)",
    "fuente": "Web oficial (sin tipos) + comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Caja Rural de Granada",
    "categoria": "Cooperativa",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D (ref. hist. 30 años)",
    "financiacionMax": "N/D (ref. hist. 80%; 70% 2ª)",
    "diferencial": "",
    "vinculaciones": "Nómina + seguros vida/hogar/protección pagos + plan pensiones + tarjeta (hist. no confirmada vigente)",
    "comisiones": "Apertura: N/D vigente (hist. 0%); amortización máx. legal 2%/1,5%",
    "requisitos": "Zona Granada/Andalucía oriental; web mantiene Fija activa sin tipos; único dato (HelpMyCash feb-2023) marcado \"ya no se comercializa\"",
    "fuente": "Web oficial (sin tipos) + comparador (feb-2023, descatalogada), jul-2026 / Baja"
  },
  {
    "banco": "Caja Rural de Granada",
    "categoria": "Cooperativa",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D (ref. hist. 30 años)",
    "financiacionMax": "N/D (ref. hist. 80%; 70% 2ª)",
    "diferencial": "N/D vigente (ref. hist. Euríbor +1,25% bonif. / +2,25% sin, tras 1er año fijo)",
    "vinculaciones": "Nómina + seguros + plan pensiones + tarjeta (hist. no confirmada); combinable hasta 1 p.p.",
    "comisiones": "Apertura: N/D vigente (hist. 0%); amortización máx. legal 2%/1,5%",
    "requisitos": "Zona Granada; web mantiene Variable activa sin tipos; dato (nov-2022) \"ya no se comercializa\"",
    "fuente": "Web oficial (sin tipos) + comparador (nov-2022, descatalogada), jul-2026 / Baja"
  },
  {
    "banco": "Caja Rural de Granada",
    "categoria": "Cooperativa",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D (ref. hist. 30 años, mín. 5)",
    "financiacionMax": "N/D (ref. hist. 80%; 70% 2ª; máx. 480.000€)",
    "diferencial": "Tramo fijo hist. 5 años; después Euríbor +0,85% (bonif.) / +1,85% (sin)  no confirmado vigente",
    "vinculaciones": "Nómina + seguros + plan pensiones + tarjeta (hist. no confirmada); combinable hasta 1 p.p.",
    "comisiones": "Apertura: N/D vigente (hist. 0%); amortización máx. legal 2%/1,5%",
    "requisitos": "Zona Granada; web mantiene Mixta activa sin tipos; dato (feb-2023) \"ya no se comercializa\"",
    "fuente": "Web oficial (sin tipos) + comparador (feb-2023, descatalogada), jul-2026 / Baja"
  },
  {
    "banco": "Caja Rural del Sur",
    "categoria": "Cooperativa",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "2,70% / 3,70%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina/pensión + seguro hogar + seguro vida + tarjeta + recibos domiciliados; desglose % no publicado",
    "comisiones": "Apertura: sin comisión; amortización máx. legal 2% (10 primeros años)/1,5% (después)",
    "requisitos": "Zona Andalucía occidental (Sevilla/Huelva/Cádiz); web no publica TIN/TAE (remite a simulador Grupo Caja Rural/oficina)",
    "fuente": "Web oficial (sin tipos) + comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Caja Rural del Sur",
    "categoria": "Cooperativa",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,80% / Eur+1,30%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Euríbor +0,80% (bonif.) / +1,30% (sin bonif.); sin tramo fijo inicial",
    "vinculaciones": "Nómina/pensión + seguro hogar + seguro vida + tarjeta + recibos; desglose % no publicado",
    "comisiones": "Apertura: sin comisión; amortización máx. legal 2%/1,5%",
    "requisitos": "Zona Andalucía occidental; web no publica diferencial (remite a simulador/oficina)",
    "fuente": "Web oficial (sin tipos) + comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Caja Rural del Sur",
    "categoria": "Cooperativa",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,55% / 3,70%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo 5 años al 2,55% TIN; después Euríbor +0,90% (bonif.) / +1,40% (sin bonif.)",
    "vinculaciones": "Nómina/pensión + seguro hogar + seguro vida + tarjeta + recibos; desglose % no publicado",
    "comisiones": "Apertura: sin comisión; amortización máx. legal 2%/1,5%",
    "requisitos": "Zona Andalucía occidental; web no publica tipos (remite a simulador/oficina)",
    "fuente": "Web oficial (sin tipos) + comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Caja Rural de Asturias",
    "categoria": "Cooperativa",
    "producto": "Vivienda Tipo Fijo",
    "tipo": "Fija",
    "tin": "3,05% / 4,20%",
    "tae": "3,61% / 4,41%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina/pensión ≥1.800€/mes −0,50 p.p.; seguro hogar Grupo CR −0,20; seguro vida −0,35; tarjeta crédito (≥120€/mes) −0,10; bonif. máx. acumulable 1,15 p.p.",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (resto)",
    "requisitos": "80% tasación; titular <75 años al vencimiento",
    "fuente": "FIPRE oficial (jun-2024) + comparador hipotecas.me, jul-2026 / Alta-Media",
    "tinAnterior": "2,80% / 3,80%"
  },
  {
    "banco": "Caja Rural de Asturias",
    "categoria": "Cooperativa",
    "producto": "Tú Eliges Variable Plus",
    "tipo": "Variable",
    "tin": "Eur+0,65% / Eur+1,80%",
    "tae": "3,44% / 4,13%",
    "plazoMax": "35 años",
    "financiacionMax": "80%",
    "diferencial": "Euríbor +0,65% (bonif. máx) a +1,80% (sin bonif.); primeros 12 meses a tipo fijo",
    "vinculaciones": "Nómina/pensión/autónomo −0,50; seguro hogar −0,20; seguro vida −0,35; tarjeta −0,10; fondos ≥25.000€ −0,20; saldo cuenta ≥25.000€ −0,15; plan pensiones ≥15.000€ −0,20 (bonif. máx. 1,15 p.p.)",
    "comisiones": "Apertura 0%; amortización tramo variable 0,15% (5 años)/0% después; subrogación a fijo 0,05% (3 años)",
    "requisitos": "80% tasación; titular <75 años al vencimiento; revisión anual",
    "fuente": "FIPRE oficial (03-feb-2026), jul-2026 / Alta",
    "taeAnterior": "4,70% / 5,41%"
  },
  {
    "banco": "Caja Rural de Asturias",
    "categoria": "Cooperativa",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo 5 años al 2,85%; después Euríbor +0,75% (bonif.) / +1,25% (sin bonif.)",
    "vinculaciones": "Vinculación media estimada (nómina, seguros vida/hogar, tarjeta); desglose exacto no publicado para esta modalidad",
    "comisiones": "Apertura 0% (estimado); amortización N/D",
    "requisitos": "Solo zona Asturias; no se localizó FIPRE oficial específico de esta modalidad",
    "fuente": "Comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Bantierra",
    "categoria": "Cooperativa",
    "producto": "Fija Online",
    "tipo": "Fija",
    "tin": "2,44% / 3,79%",
    "tae": "2,92%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina ≥800€/mes −0,50%; seguro vida CRA −0,50%; seguro hogar CRA −0,30%; sostenibilidad vivienda −0,05%; bonif. máx. combinada −1,35 p.p.",
    "comisiones": "Apertura 0% (estimado); amortización N/D",
    "requisitos": "Importe mín. 80.000€; primeros 6 meses TIN introductorio ≈2,44%-2,49%; contratación 100% online",
    "fuente": "Simulador/páginas oficiales (no accesibles por fetch) + prensa colaboradora, jul-2026 / Media"
  },
  {
    "banco": "Bantierra",
    "categoria": "Cooperativa",
    "producto": "Variable Online",
    "tipo": "Variable",
    "tin": "Eur+0,55% / Eur+1,60%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Euríbor +0,55% (bonif. máx) a +1,60% (sin bonif.); primeros 12 meses TIN fijo 1,50%",
    "vinculaciones": "Nómina ≥800€/mes −0,40%; seguro vida CRA −0,40%; seguro hogar CRA −0,20%; sostenibilidad −0,05%; bonif. máx. combinada −1,05 p.p.",
    "comisiones": "Apertura 0% (estimado); amortización N/D",
    "requisitos": "Importe mín. 80.000€; contratación 100% online con gestor de apoyo",
    "fuente": "Simulador/páginas oficiales (no accesibles por fetch), jul-2026 / Media"
  },
  {
    "banco": "Bantierra",
    "categoria": "Cooperativa",
    "producto": "Mixta Online (Mixta 5)",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo 5 años desde 1,79% TIN; después Euríbor +1,99%",
    "vinculaciones": "Vinculación estimada similar a fija/variable (nómina, seguros); desglose no publicado para esta modalidad",
    "comisiones": "Apertura 0% (estimado); amortización N/D",
    "requisitos": "\"Hipoteca Mixta 5\"; contratación 100% online; importe mín. estimado 80.000€",
    "fuente": "Prensa colaboradora + noticia lanzamiento, jul-2026 / Media"
  },
  {
    "banco": "Globalcaja",
    "categoria": "Cooperativa",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "2,70% / 3,70%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, seguro hogar, seguro vida, tarjeta débito/crédito (desglose exacto no publicado)",
    "comisiones": "Apertura 0%; amortización N/D (tope legal orientativo 2%/1,5%)",
    "requisitos": "FIPRE oficial en web (may-2026) no accesible por bloqueo técnico; datos de comparador",
    "fuente": "Comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Globalcaja",
    "categoria": "Cooperativa",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,99% / Eur+1,50%",
    "tae": "N/D",
    "plazoMax": "35 años (web) / 30 años (comparador)",
    "financiacionMax": "80% (hasta 100% con aval ICO, perfiles solventes)",
    "diferencial": "Euríbor +0,99% a +1,50% según vinculación; TIN 2,19% primer año",
    "vinculaciones": "Nómina/ingresos ≥1.000€/mes, seguro hogar, seguro vida; bonif. combinada hasta 1,20 p.p.",
    "comisiones": "Apertura 0%; amortización 0,25%-0,50%; subrogación 0,25%-0,50%",
    "requisitos": "Solo Castilla-La Mancha y zonas próximas; suma edad+plazo ≤75 años",
    "fuente": "Web oficial Globalcaja + comparadores, jul-2026 / Media"
  },
  {
    "banco": "Globalcaja",
    "categoria": "Cooperativa",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80% (hasta 100% con aval ICO)",
    "diferencial": "Tramo fijo 3 o 5 años (2,5%-3,0%); después Euríbor +aprox. 1,35%",
    "vinculaciones": "Nómina ≥1.000€/mes, tarjeta crédito, seguro vida (≥70% capital), seguro hogar; bonif. combinada hasta 1% TIN (ej. 3 vinculaciones: −0,70%)",
    "comisiones": "Apertura 0%; amortización parcial sin comisión; total anticipada con comisión (% no especificado)",
    "requisitos": "Edad máx. 70 años al vencimiento; suma edad+plazo ≤75 años; ingresos mín. 700€/mes",
    "fuente": "Web oficial Globalcaja + comparadores, jul-2026 / Media"
  },
  {
    "banco": "Caja Rural Central",
    "categoria": "Cooperativa",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80% (1ª vivienda; menor entre tasación y compraventa)",
    "diferencial": "",
    "vinculaciones": "Bonificable con productos (nómina, seguros, condición de socio); porcentajes no publicados",
    "comisiones": "N/D (no publicadas en web)",
    "requisitos": "Tipos solo vía simulador u oficina; ámbito Orihuela / C. Valenciana-Murcia",
    "fuente": "Web oficial ruralcentral.es (sin cifras), jul-2026 / Media-Baja"
  },
  {
    "banco": "Caja Rural Central",
    "categoria": "Cooperativa",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80% (1ª vivienda; menor entre tasación y compraventa)",
    "diferencial": "Diferencial N/D; estructura confirmada: tipo fijo el 1er año y resto referenciado a Euríbor",
    "vinculaciones": "Reduce cuota con productos (nómina, seguros, socio); porcentajes no publicados",
    "comisiones": "N/D (no publicadas en web)",
    "requisitos": "Solo vía formulario/oficina; sin ficha con cifras propias",
    "fuente": "Web oficial ruralcentral.es (sin cifras), jul-2026 / Media-Baja"
  },
  {
    "banco": "Caja Rural Central",
    "categoria": "Cooperativa",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "30 años (asumido, no confirmado)",
    "financiacionMax": "80% (asumido, no confirmado)",
    "diferencial": "N/D",
    "vinculaciones": "N/D",
    "comisiones": "N/D",
    "requisitos": "Producto mencionado en el site (\"Hipotecas Mixtas\") sin ficha ni condiciones accesibles; solicitar en oficina",
    "fuente": "Web oficial ruralcentral.es (solo nombre), jul-2026 / Baja"
  },
  {
    "banco": "Cajasiete",
    "categoria": "Cooperativa",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "2,70% / 3,70%",
    "tae": "3,331% / 3,942%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (menor entre compra y tasación)",
    "diferencial": "",
    "vinculaciones": "Nómina >1.200€/mes −0,15; seguro vida (100% préstamo) −0,25; seguro hogar −0,25; seguro protección pagos −0,25; plan pensiones −0,15; fondos −0,15; tarjeta crédito −0,10; título socio −0,10; 3 recibos −0,05; cert. energético −0,05 (bonif. máx. conjunta 1 punto)",
    "comisiones": "Apertura 0%; amortización 2% (10 primeros años)/1,5% (resto), según Folleto de Tarifas",
    "requisitos": "Exclusiva vivienda habitual; ej. 150.000€/30a; tasación 280€",
    "fuente": "Web oficial cajasiete.com + Folleto de Tarifas oficial, jul-2026 / Alta"
  },
  {
    "banco": "Cajasiete",
    "categoria": "Cooperativa",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,50% / Eur+1,50%",
    "tae": "3,757% / 4,375%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (menor entre compra y tasación)",
    "diferencial": "Euríbor +0,50% (bonif.) / +1,50% (sin bonif.); 1 año inicial a tipo fijo 1,75%",
    "vinculaciones": "Idénticas a fija: nómina −0,15; vida −0,25; hogar −0,25; prot. pagos −0,25; pensiones −0,15; fondos −0,15; tarjeta −0,10; socio −0,10; recibos −0,05; cert. energético −0,05 (máx. 1 punto)",
    "comisiones": "Apertura 0%; amortización 0,25% (3 años) o 0,15% (5 años) según pacto, 0% después",
    "requisitos": "Exclusiva vivienda habitual; ej. 150.000€/30a",
    "fuente": "Web oficial cajasiete.com + Folleto de Tarifas oficial, jul-2026 / Alta",
    "taeAnterior": "3,28%"
  },
  {
    "banco": "Cajasiete",
    "categoria": "Cooperativa",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,35% / 3,35%",
    "tae": "3,623% / 4,236%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (menor entre compra y tasación)",
    "diferencial": "Tramo fijo 5 años (2,35%/3,35% TIN); después Euríbor +0,55% (bonif.) / +1,55% (sin bonif.)",
    "vinculaciones": "Nómina −0,20; vida −0,30; hogar −0,30; pensiones −0,15; fondos −0,20; tarjeta −0,15; socio −0,10; 3 recibos −0,05; cert. energético −0,05 (máx. 1 punto)",
    "comisiones": "Apertura 0%; amortización tramo fijo 2%/1,5% (10a/resto), tramo variable 0,25% (3a) o 0,15% (5a), 0% después",
    "requisitos": "Exclusiva vivienda habitual; ej. 150.000€/30a",
    "fuente": "Web oficial cajasiete.com + Folleto de Tarifas oficial, jul-2026 / Alta",
    "taeAnterior": "3,10%"
  },
  {
    "banco": "Caixa Popular",
    "categoria": "Cooperativa",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "2,70% / 2,95%",
    "tae": "N/D",
    "plazoMax": "35 años",
    "financiacionMax": "80% (hasta 100% perfil \"Premium\" con nómina ≥2.500€)",
    "diferencial": "",
    "vinculaciones": "Nómina >1.800€/mes; seguro hogar; seguro vida (≥70% capital); seguro protección pagos; +0,25 p.p. adic. por cert. energético A/B; desglose individual no confirmado",
    "comisiones": "Apertura 0% (ficha; misma fuente cita 1% en \"estándar\": inconsistente); amortización N/D (tope legal 2%/1,5%)",
    "requisitos": "Principalmente C. Valenciana; tipo fijo ligado a perfil renta alta/\"Premium\"; confirmar en oficina",
    "fuente": "Comparador hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Caixa Popular",
    "categoria": "Cooperativa",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "Eur+0,90% / Eur+1,90%",
    "tae": "5,27%",
    "plazoMax": "35 años",
    "financiacionMax": "80%",
    "diferencial": "Euríbor +0,90% (bonif.) / +1,90% (sin bonif.); 1 año inicial a tipo fijo 1,90%",
    "vinculaciones": "Nómina >1.800€/mes, consumo ≥3.000€/año tarjeta, seguro vida, seguro hogar, seguro protección pagos: −0,20 cada uno (máx. conjunta 1 punto)",
    "comisiones": "Apertura 1% (mín. 300€); sin comisión de amortización anticipada",
    "requisitos": "Solo 1ª vivienda; C. Valenciana; edad 18-70 años",
    "fuente": "Comparador Kelisto + portal oficial, jul-2026 / Media"
  },
  {
    "banco": "Caixa Popular",
    "categoria": "Cooperativa",
    "producto": "Mixta",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,20% / 3,40%",
    "tae": "3,19%",
    "plazoMax": "35 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo 3 años (2,20%/3,40% TIN); después Euríbor +0,55% (bonif.) / +1,75% (sin bonif.)",
    "vinculaciones": "Nómina ≥1.800€/mes −0,20; tarjeta (≥3.000€/año) −0,10; seguro vida (≥70% capital) −0,30; seguro hogar −0,20; prot. pagos −0,30; incapacidad laboral temporal −0,15; domiciliación recibos −0,10 (máx. conjunta 1,20 puntos)",
    "comisiones": "Apertura 1% (mín. 300€); sin comisión de amortización anticipada",
    "requisitos": "Solo 1ª vivienda; C. Valenciana; ningún titular >70 años al vencimiento",
    "fuente": "Comparador Kelisto, jul-2026 / Media"
  },
  {
    "banco": "Caixa Rural Galega",
    "categoria": "Cooperativa",
    "producto": "a Tipo Fijo",
    "tipo": "Fija",
    "tin": "4,10% / 4,50%",
    "tae": "4,16% / 4,78%",
    "plazoMax": "25 años (tabla llega a 26-30 años)",
    "financiacionMax": "80% sobre tasación o compraventa (el menor)",
    "diferencial": "(100% fijo)",
    "vinculaciones": "Seguro daños/hogar obligatorio (no bonifica); \"no se establecen bonificaciones por productos combinados\"",
    "comisiones": "Apertura 1,00%; amortización 2% (10 primeros años)/1,5% (resto)",
    "requisitos": "Finalidad vivienda habitual/2ª/garaje/construcción; edad+plazo ≤75 años; tasación ≈235€",
    "fuente": "FIPRE oficial caixaruralgalega.gal (PDF), abr-2026 / Alta",
    "tinAnterior": "2,44% / 3,79%"
  },
  {
    "banco": "Caixa Rural Galega",
    "categoria": "Cooperativa",
    "producto": "Te lo Mereces",
    "tipo": "Variable",
    "tin": "Eur+0,95% / Eur+1,55%",
    "tae": "3,92% / 4,21%",
    "plazoMax": "30 años",
    "financiacionMax": "80% sobre tasación o compraventa (el menor)",
    "diferencial": "Euríbor +0,95% a +1,55%; 12 meses de tramo fijo inicial",
    "vinculaciones": "Nómina/pensión ≥900€/mes −0,20%; tarjeta crédito usada −0,10%; seguro hogar (grupo) −0,15%; seguro vida ≥70% capital (grupo) −0,15%; máx. −0,60 puntos",
    "comisiones": "Apertura 0,75%; amortización tramo variable 0,15% (5a)/0% después; subrogación a fijo 0,05% (3a)",
    "requisitos": "Seguro daños obligatorio; edad+plazo ≤75 años",
    "fuente": "FIPRE oficial (feb-2025; estructura vigente), jul-2026 / Alta",
    "tinAnterior": "Eur+0,64% / Eur+1,60%"
  },
  {
    "banco": "Caixa Rural Galega",
    "categoria": "Cooperativa",
    "producto": "Te lo Mereces Mixto 10",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 3,10% / 1,25%",
    "tae": "3,85% / 3,81%",
    "plazoMax": "30 años",
    "financiacionMax": "80% sobre tasación o compraventa (el menor)",
    "diferencial": "Euríbor +1,25% a +1,85%; 10 años de tramo fijo inicial",
    "vinculaciones": "Nómina ≥900€/mes −0,20%; tarjeta crédito −0,10%; seguro hogar (grupo) −0,15%; seguro vida ≥70% capital (grupo) −0,15%; máx. −0,60 pts (sobre tramo variable)",
    "comisiones": "Apertura 1,00%; amortización tramo fijo 2% (10a)/1,5% (resto); tramo variable 0,15% (5a)/0% después",
    "requisitos": "Edad+plazo ≤75 años; existen variantes \"Mixto 5\" y \"Más\" con distinto tramo fijo",
    "fuente": "FIPRE oficial (PDF), mar-2026 / Alta"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Fija",
    "tipo": "Fija",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D publicado (comparadores citan hasta 30 años)",
    "financiacionMax": "N/D publicado (comparadores citan hasta 80%)",
    "diferencial": "",
    "vinculaciones": "N/D exacto; el grupo suele exigir nómina, seguros hogar y vida, y aportación a plan de pensiones (orientativo ≥600€/año); cuantía no publicada",
    "comisiones": "N/D (no publicadas)",
    "requisitos": "Web remite a simulador y a estudio en oficina (FEIN); zona principal País Vasco y Navarra",
    "fuente": "Web oficial laboralkutxa.com (sin cifras) + comparadores, jul-2026 / Baja"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Variable",
    "tipo": "Variable",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D publicado",
    "financiacionMax": "N/D publicado (comparadores citan hasta 80%)",
    "diferencial": "Euríbor + diferencial no confirmado oficialmente",
    "vinculaciones": "N/D exacto; previsiblemente nómina + seguros, similar a otros productos del grupo",
    "comisiones": "N/D",
    "requisitos": "Sin publicación oficial de tipos; simulador propio; comparadores discrepan entre sí (datos no oficiales/desactualizados)",
    "fuente": "Comparadores (hipotecas.me/rankia/roams), sin confirmación oficial, jul-2026 / Baja"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Estable",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "Hasta 30 años (10 fijos + 20 variables), cifra de comparador no confirmada",
    "financiacionMax": "N/D confirmado (comparador antiguo citaba 80%)",
    "diferencial": "10 años de tramo fijo inicial + resto variable; diferencial no confirmado vigente",
    "vinculaciones": "Nómina; tarjeta VISA Laboral Kutxa; seguro hogar y vida; aportación plan pensiones ≥600€ (estructura de comparador; bonif. no publicada)",
    "comisiones": "Apertura hist. 0,50% (no confirmada vigente); amortización N/D",
    "requisitos": "Comparador (may-2026) declara que ya no hay info pública; \"consulta al banco\"",
    "fuente": "busconomico.com + web oficial, jul-2026 / Baja"
  },
  {
    "banco": "Banco Cooperativo Español",
    "categoria": "Cooperativa",
    "producto": "Fija \"Te lo Mereces Ahora",
    "tipo": "Fija",
    "tin": "3,35% / 4,20%",
    "tae": "4,06% / 4,42%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (1ª y 2ª vivienda); importe máx. 480.000€",
    "diferencial": "(100% fijo)",
    "vinculaciones": "Domiciliar ingresos ≥1.000€/mes −0,40%; tarjeta crédito −0,10%; seguro hogar −0,10%; seguro vida −0,25% (máx. −0,85 pts, 4 vinculaciones)",
    "comisiones": "Apertura 0,25%; amortización N/D (no detallada)",
    "requisitos": "Exclusiva para ingresos 1.000-1.800€/mes; edad máx. 70 años al final; variantes \"Ya\" y \"por ser joven\"",
    "fuente": "Comparador HelpMyCash (01-jul-2026) + ficha bancocooperativo.es, jul-2026 / Media-Alta"
  },
  {
    "banco": "Banco Cooperativo Español",
    "categoria": "Cooperativa",
    "producto": "Variable \"Te lo Mereces Ahora",
    "tipo": "Variable",
    "tin": "Eur+0,75% / Eur+1,60%",
    "tae": "4,28% / 4,64%",
    "plazoMax": "30 años (patrón general)",
    "financiacionMax": "80% (patrón general)",
    "diferencial": "Euríbor +0,75% a +1,60%; sin tramo fijo relevante (revisión anual desde el inicio)",
    "vinculaciones": "Domiciliar ingresos ≥1.000€/mes −0,40%; tarjeta −0,10%; seguro hogar −0,10%; seguro vida −0,25% (máx. −0,85 pts)",
    "comisiones": "Apertura 0,25%; amortización N/D",
    "requisitos": "Exclusiva para ingresos desde 1.000€/mes; variantes \"Ya\" (Eur+0,55%/+1,55%) y \"por ser joven\" (≤30 años)",
    "fuente": "Comparador HelpMyCash (01-jul-2026), jul-2026 / Media-Alta"
  },
  {
    "banco": "Banco Cooperativo Español",
    "categoria": "Cooperativa",
    "producto": "Mixta \"Te lo Mereces",
    "tipo": "Mixta",
    "tin": "Tramo fijo: 2,95% / 3,95%",
    "tae": "4,01% / 4,50%",
    "plazoMax": "30 años (mín. 5 años)",
    "financiacionMax": "80% (1ª y 2ª vivienda; precio inmueble tope 600.000€)",
    "diferencial": "Euríbor +0,55% a +1,55%; 5 años de tramo fijo inicial",
    "vinculaciones": "Domiciliar ingresos ≥1.800€/mes −0,55%; tarjeta −0,10%; seguro hogar −0,10%; seguro vida −0,25% (máx. −1,00 pt)",
    "comisiones": "Apertura 0,25%; amortización N/D (no detallada)",
    "requisitos": "Exclusiva para ingresos ≥1.800€/mes; edad máx. 70 años; BCE es entidad central del Grupo Caja Rural (sin red propia para particulares; distribuye vía cajas rurales asociadas)",
    "fuente": "Comparador HelpMyCash (01-jul-2026), jul-2026 / Media-Alta"
  },
  {
    "banco": "Triodos Bank",
    "categoria": "Banca ética",
    "producto": "Triodos Fija (estándar)",
    "tipo": "Fija",
    "tin": "3,63% / 4,63%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tipo fijo toda la vida; el TIN depende de la clase energética de la vivienda",
    "vinculaciones": "Domiciliación nómina + seguro de hogar (preferib. ético) + certificado de eficiencia energética; bonificación total ≈1,00 p.p. (desglose por concepto N/D)",
    "comisiones": "Apertura 0%; amortización máximos legales (fija 2% 10 primeros años/1,5% resto)",
    "requisitos": "Banca ética; vinculación media; el tipo mejora cuanto mejor es la calificación energética",
    "fuente": "hipotecas.me + roams/kelisto, jul-2026 / Media"
  },
  {
    "banco": "Triodos Bank",
    "categoria": "Banca ética",
    "producto": "Triodos Sostenible/Verde (vivienda A/B)",
    "tipo": "Fija",
    "tin": "2,70% / 3,70%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tipo fijo; mejor tarifa reservada a viviendas de alta calificación energética",
    "vinculaciones": "Cuenta corriente Triodos (vinculación baja); requiere certificado energético alto",
    "comisiones": "Apertura 0%; amortización máximos legales (2%/1,5%)",
    "requisitos": "Solo para vivienda con clase energética A/B; es la línea más competitiva de Triodos",
    "fuente": "hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Triodos Bank",
    "categoria": "Banca ética",
    "producto": "Triodos Variable",
    "tipo": "Variable",
    "tin": "Eur+0,88% / Eur+1,38%",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Euríbor +0,88% (bonif.) a +1,38% (sin bonif.); diferencial según clase energética; 1er año suele tipo fijo de salida (N/D)",
    "vinculaciones": "Domiciliación nómina + seguro hogar ético + certificado energético; reducción ≈0,50 p.p. del diferencial",
    "comisiones": "Apertura 0%; amortización variable máx legal 0,25% (3 años)/0,15% (5 años)",
    "requisitos": "Vinculación media; bonificación ligada a eficiencia energética",
    "fuente": "hipotecas.me, jul-2026 / Media"
  },
  {
    "banco": "Triodos Bank",
    "categoria": "Banca ética",
    "producto": "Triodos Mixta",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "N/D (30 años prob.)",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo inicial (hasta ~15 años) + resto Euríbor + diferencial; TIN vigente N/D",
    "vinculaciones": "N/D (vinculación similar: nómina + seguros + certificado energético)",
    "comisiones": "Apertura 0%; amortización N/D",
    "requisitos": "Figura en comparadores (Kelisto/Roams) pero NO en el catálogo actual de hipotecas.me (jul-2026, solo fija+variable); disponibilidad a confirmar",
    "fuente": "Kelisto/Roams, jul-2026 / Baja-Media"
  },
  {
    "banco": "UCI",
    "categoria": "Especialista",
    "producto": "Fija UCI",
    "tipo": "Fija",
    "tin": "2,90% / 3,45%",
    "tae": "N/D",
    "plazoMax": "25 años",
    "financiacionMax": "70% (hasta ~80-100% en casos vía Hipotecas.com)",
    "diferencial": "Tipo fijo toda la vida",
    "vinculaciones": "Domiciliación de ingresos + seguro de hogar + seguro de vida (vinculación media); bonificación total ≈0,55 p.p. (desglose N/D)",
    "comisiones": "Apertura 0% (sin comisión); amortización máximos legales fija",
    "requisitos": "EFC (no capta depósitos); origina vía prescriptores/comparadores y canal online Hipotecas.com; acepta no residentes",
    "fuente": "hipotecas.me (abr-2026), jul-2026 / Media"
  },
  {
    "banco": "UCI",
    "categoria": "Especialista",
    "producto": "Variable UCI",
    "tipo": "Variable",
    "tin": "Eur+2,09%",
    "tae": "N/D",
    "plazoMax": "25 años",
    "financiacionMax": "70%",
    "diferencial": "Euríbor +2,09% (sin bonificación adicional publicada)",
    "vinculaciones": "Domiciliación de ingresos + seguro hogar + seguro vida (vinculación media)",
    "comisiones": "Apertura 0%; amortización variable máx 0,25%/0,15%",
    "requisitos": "Diferencial alto frente a la media de mercado; acepta no residentes",
    "fuente": "hipotecas.me (abr-2026), jul-2026 / Media"
  },
  {
    "banco": "UCI",
    "categoria": "Especialista",
    "producto": "No Residente UCI",
    "tipo": "Fija",
    "tin": "2,90% / 3,60%",
    "tae": "N/D",
    "plazoMax": "25 años",
    "financiacionMax": "70% (no residentes suele 60-70%)",
    "diferencial": "Tipo fijo",
    "vinculaciones": "Seguro de hogar obligatorio (vinculación baja)",
    "comisiones": "Apertura 0%; amortización N/D",
    "requisitos": "Especializada en no residentes/compradores internacionales; nicho que pocos bancos cubren",
    "fuente": "hipotecas.me (abr-2026), jul-2026 / Media"
  },
  {
    "banco": "UCI",
    "categoria": "Especialista",
    "producto": "Mixta (canal Hipotecas.com)",
    "tipo": "Mixta",
    "tin": "N/D",
    "tae": "N/D",
    "plazoMax": "30 años",
    "financiacionMax": "Hasta 80-100%",
    "diferencial": "Tramo fijo inicial configurable de 3 a 15 años + resto Euríbor + diferencial; TIN vigente N/D",
    "vinculaciones": "Sin vinculaciones ni comisiones (canal online)",
    "comisiones": "Apertura 0%; amortización máximos legales",
    "requisitos": "Hipotecas.com es la marca digital de UCI; comercializa fija/variable/mixta sin vinculación; tipos actuales de mixta N/D",
    "fuente": "uci.com / Hipotecas.com, jul-2026 / Media"
  }
]

// Entidades consultadas que actualmente no comercializan hipotecas residenciales
export const ENTIDADES_SIN_OFERTA: { banco: string; nota: string }[] = [
  {
    "banco": "N26",
    "nota": "N26 no ofrece hipotecas en España; solo cuentas y préstamos personales (1.000-15.000€); sin planes anunciados para 2026"
  },
  {
    "banco": "Trade Republic",
    "nota": "Trade Republic no ofrece hipotecas en España; centrado en bróker/inversión y cuenta remunerada; sin producto hipotecario"
  },
  {
    "banco": "Cetelem",
    "nota": "BNP Paribas Personal Finance España (marca Cetelem): préstamos personales, tarjeta, cuentas, depósitos y seguros. NO ofrece préstamo hipotecario de compra de vivienda; el \"Préstamo Reforma y hogar\" es préstamo personal al consumo"
  },
  {
    "banco": "Santander Consumer Finance",
    "nota": "División de crédito al consumo del Grupo Santander (auto, préstamos personales, tarjetas, financiación en punto de venta). NO concede hipotecas de vivienda; las hipotecas del grupo las da Banco Santander S.A."
  },
  {
    "banco": "BNP Paribas",
    "nota": "Actividad retail en España = inversión, wealth management y seguros (Cardif); \"Personal Investors\" es brokerage. Financiación inmobiliaria solo a medida en banca privada/corporativa"
  },
  {
    "banco": "Bigbank",
    "nota": "Banco estonio de préstamos al consumo (500-15.000€) y depósitos a plazo. Nunca ha ofrecido hipotecas residenciales en España; sin nueva concesión de préstamos en España desde ~2021"
  },
  {
    "banco": "Fiare Banca Ética",
    "nota": "A particulares solo cuentas, tarjetas, depósitos y \"Préstamos Energía\". Su producto de vivienda es \"vivienda cooperativa\" (financia a la cooperativa, no al particular). No concede hipoteca de compra individual"
  }
]
