// Revisión editorial de fuentes oficiales: 24 de septiembre de 2026.
// Cada oferta conserva su enlace y fecha. Consultar no equivale a un tipo cero.
// Las entradas antiguas no confirmadas se conservan aparte, sin precios caducados.

export interface OfertaHipoteca {
  banco: string
  categoria: string
  producto: string
  tipo: 'Fija' | 'Variable' | 'Mixta' | 'Fija/Variable' | 'Fija/Variable/Mixta' | 'Variable/Mixta' | 'Consultar'
  tin: string
  tae: string
  plazoMax: string
  financiacionMax: string
  diferencial: string
  vinculaciones: string
  comisiones: string
  requisitos: string
  fuente: string
  urlFuente: string
  fechaRevision: string
  estado: 'publicada' | 'consultar'
  // Solo añadir históricos cuando producto, plazo, bonificaciones y fuente sean comparables.
  tinAnterior?: string
  taeAnterior?: string
}

export const FECHA_DATOS_ISO = '2026-09-24'
export const FECHA_DATOS = '24 de septiembre de 2026'
export const fechaDatos = new Date(`${FECHA_DATOS_ISO}T00:00:00Z`)
export function fechaOferta(iso: string, lang: 'es' | 'en'): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString(lang === 'en' ? 'en-GB' : 'es-ES', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' })
}

export const OFERTAS_HIPOTECAS: OfertaHipoteca[] = [
  {
    "banco": "CaixaBank",
    "categoria": "Grande",
    "producto": "Hipoteca CasaFácil Fijo",
    "tipo": "Fija",
    "tin": "2,85% / 3,85%",
    "tae": "4,259% / 4,317%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina, recibos, tarjeta, seguros de hogar y vida y alarma, según bonificadores de CasaFácil.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 30 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.caixabank.es/particular/hipotecas.html",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Hipoteca Santander Fija",
    "tipo": "Fija",
    "tin": "2,96% / 3,96%",
    "tae": "3,65% / 4,16%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre tasación)",
    "diferencial": "2,96% los primeros 6 meses en ambos casos; después se aplica la pareja de tipos indicada.",
    "vinculaciones": "Ingresos y Bizum o tarjeta, seguros e inversiones: bonificación máxima de 1 punto. Consultar importes y combinaciones.",
    "comisiones": "Apertura 0%. Reembolso: hasta 2% los primeros 10 años y 1,5% después, limitado a la pérdida financiera.",
    "requisitos": "Ejemplo: 150.000 € a 30 años. Oferta online válida hasta el 15/10/2026. Segunda vivienda: hasta 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancosantander.es/particulares/hipotecas/hipoteca-fija",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Santander",
    "tipo": "Mixta",
    "tin": "2,34% / 3,34% (tramo fijo)",
    "tae": "3,82% / 4,30%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "2,34% los primeros 6 meses; después 5 años al tipo fijo indicado. Resto: E+0,74% / E+1,74%.",
    "vinculaciones": "Ingresos y Bizum o tarjeta, seguros e inversiones: bonificación máxima de 1 punto. Consultar importes y combinaciones.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancosantander.es/particulares/hipotecas/hipoteca-mixta",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banco Santander",
    "categoria": "Grande",
    "producto": "Hipoteca Santander Variable",
    "tipo": "Variable",
    "tin": "1,84% (primeros 6 meses)",
    "tae": "4,42% / 4,92%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Desde el mes 7: E+0,84% / E+1,84%.",
    "vinculaciones": "Ingresos y Bizum o tarjeta, seguros e inversiones: bonificación máxima de 1 punto. Consultar importes y combinaciones.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancosantander.es/particulares/hipotecas/hipoteca-variable",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "BBVA",
    "categoria": "Grande",
    "producto": "Hipoteca Fija BBVA",
    "tipo": "Fija",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "Domiciliación de ingresos, seguro de hogar y seguro de amortización del préstamo.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "La página confirma el producto, pero no permite verificar un precio completo. Solicita una simulación y la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bbva.es/personas/productos/hipotecas/hipoteca-fija.html",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "BBVA",
    "categoria": "Grande",
    "producto": "Hipoteca Variable BBVA",
    "tipo": "Variable",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "Domiciliación de ingresos, seguro de hogar y seguro de amortización del préstamo.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "La página confirma el producto, pero no permite verificar un precio completo. Solicita una simulación y la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bbva.es/personas/productos/hipotecas/hipoteca-variable.html",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Hipoteca Fija Bonificada",
    "tipo": "Fija",
    "tin": "2,75% / 3,75%",
    "tae": "3,58% / 4,23%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "Nómina, seguro vida, seguro hogar, seguro protección de pagos",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 30 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancsabadell.com/bsnacional/es/particulares/hipotecas/hipoteca-fija/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Hipoteca Variable Sabadell",
    "tipo": "Variable",
    "tin": "1,50% / 2,50% (primer año)",
    "tae": "4,12% / 4,78%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Desde el segundo año: E+0,50% / E+1,50%.",
    "vinculaciones": "Nómina, seguro vida, seguro hogar, seguro protección de pagos",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 30 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancsabadell.com/bsnacional/es/particulares/hipotecas/hipoteca-variable/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Sabadell 3",
    "tipo": "Mixta",
    "tin": "1,80% / 2,70%",
    "tae": "3,72% / 4,61%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Tramo fijo: 3 años. Resto: E+0,70% / E+1,60%.",
    "vinculaciones": "Nómina, seguro vida, seguro hogar, seguro protección de pagos",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 30 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancsabadell.com/bsnacional/es/particulares/hipotecas/hipoteca-mixta/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Sabadell 5",
    "tipo": "Mixta",
    "tin": "2,10% / 3,00%",
    "tae": "3,78% / 4,66%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Tramo fijo: 5 años. Resto: E+1,00% / E+1,90%.",
    "vinculaciones": "Nómina, seguro vida, seguro hogar, seguro protección de pagos",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 30 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancsabadell.com/bsnacional/es/particulares/hipotecas/hipoteca-mixta/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banco Sabadell",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Sabadell 7",
    "tipo": "Mixta",
    "tin": "2,45% / 3,35%",
    "tae": "3,89% / 4,77%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Tramo fijo: 7 años. Resto: E+1,30% / E+2,20%.",
    "vinculaciones": "Nómina, seguro vida, seguro hogar, seguro protección de pagos",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 30 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancsabadell.com/bsnacional/es/particulares/hipotecas/hipoteca-mixta/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Hipoteca Fija Bankinter",
    "tipo": "Fija",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80% (60% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "Cuenta Bankinter, seguros y, según modalidad, plan de pensiones; consultar bonificadores.",
    "comisiones": "Apertura 500 €; consultar reembolso anticipado en la FEIN.",
    "requisitos": "La página confirma el producto, pero no permite verificar un precio completo. Solicita una simulación y la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bankinter.com/banca/hipotecas-prestamos/hipotecas/hipoteca-fija",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Hipoteca Variable Bankinter",
    "tipo": "Variable",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80% (60% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "Cuenta Bankinter, seguros y, según modalidad, plan de pensiones; consultar bonificadores.",
    "comisiones": "Apertura 500 €; consultar reembolso anticipado en la FEIN.",
    "requisitos": "La página confirma el producto, pero no permite verificar un precio completo. Solicita una simulación y la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bankinter.com/banca/hipotecas-prestamos/hipotecas/hipoteca-variable",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Bankinter",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Bankinter",
    "tipo": "Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80% (60% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "Cuenta Bankinter, seguros y, según modalidad, plan de pensiones; consultar bonificadores.",
    "comisiones": "Apertura 500 €; consultar reembolso anticipado en la FEIN.",
    "requisitos": "La página confirma el producto, pero no permite verificar un precio completo. Solicita una simulación y la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bankinter.com/banca/hipotecas-prestamos/hipotecas/hipoteca-mixta",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Fija Unicaja",
    "tipo": "Fija",
    "tin": "3,10% / 4,10%",
    "tae": "4,09% / 4,24%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Primeros 6 meses: 3,15% en ambos casos; después, el tipo indicado.",
    "vinculaciones": "Nómina, recibos, tarjeta, seguros hogar y vida, fondos/plan de pensiones",
    "comisiones": "Apertura 0,15%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Condiciones para nómina desde 2.000 € netos/mes. Ejemplo: 150.000 € a 25 años; otros ingresos tienen precios diferentes.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.unicajabanco.es/es/particulares/hipotecas-y-prestamos/hipotecas/hipoteca-tipo-fijo",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Variable Unicaja (nómina +2.000 €)",
    "tipo": "Variable",
    "tin": "1,90% (primer año)",
    "tae": "4,33% / 4,44%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Desde el segundo año: E+0,55% / E+1,55%.",
    "vinculaciones": "Nómina, recibos, tarjeta, seguros hogar y vida, fondos/plan de pensiones",
    "comisiones": "Apertura 0,15%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Condiciones para nómina desde 2.000 € netos/mes. Ejemplo: 150.000 € a 25 años; otros ingresos tienen precios diferentes.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.unicajabanco.es/es/particulares/hipotecas-y-prestamos/hipotecas/hipoteca-tipo-variable",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Unicaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta Unicaja",
    "tipo": "Mixta",
    "tin": "2,20% / 3,20%",
    "tae": "3,99% / 4,18%",
    "plazoMax": "",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Tramo fijo: 5 años. Resto: E+0,60% / E+1,60%.",
    "vinculaciones": "Nómina, recibos, tarjeta, seguros hogar y vida, fondos/plan de pensiones",
    "comisiones": "Apertura 0,15%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Condiciones para nómina desde 2.000 € netos/mes. Ejemplo: 150.000 € a 25 años; otros ingresos tienen precios diferentes.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.unicajabanco.es/es/particulares/hipotecas-y-prestamos/hipotecas/hipoteca-mixta",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Abanca",
    "categoria": "Grande",
    "producto": "Hipoteca Mari Carmen Fija",
    "tipo": "Fija",
    "tin": "2,95% / 3,95%",
    "tae": "5,44% / 4,61%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Precios del ejemplo a 15 años; cambian con el plazo. La TAE bonificada supera a la no bonificada.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.abanca.com/es/hipotecas/hipoteca-maricarmen-fija/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Abanca",
    "categoria": "Grande",
    "producto": "Hipoteca Mari Carmen Variable",
    "tipo": "Variable",
    "tin": "2,35% / 3,35% (primer año)",
    "tae": "5,70% / 5,04%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Desde el segundo año: E+0,60% / E+1,60%.",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Valora el coste de los productos: en este ejemplo, la TAE bonificada es superior a la no bonificada.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.abanca.com/es/hipotecas/hipoteca-maricarmen/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Abanca",
    "categoria": "Grande",
    "producto": "Hipoteca Mari Carmen Mixta",
    "tipo": "Mixta",
    "tin": "2,05% / 3,05%",
    "tae": "5,20% / 4,52%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo: 5 años. Resto: E+0,60% / E+1,60%.",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Valora el coste de los productos: en este ejemplo, la TAE bonificada es superior a la no bonificada.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.abanca.com/es/hipotecas/hipoteca-mixta/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Vamos Fija",
    "tipo": "Fija",
    "tin": "2,55% / 3,55%",
    "tae": "3,49% / 3,80%",
    "plazoMax": "25 años",
    "financiacionMax": "80% (95% ≤35 años)",
    "diferencial": "Primer año: 2,55% en ambos casos; después, el tipo indicado.",
    "vinculaciones": "Nómina ≥2.500 €/mes, 12 operaciones de tarjeta por semestre, 3 recibos, seguros de hogar y vida y 75 €/mes a fondos.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Desde 100.000 €; vivienda habitual. Ejemplo: 150.000 € a 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.ibercaja.es/particulares/hipotecas-prestamos/hipotecas/hipoteca-vamos-fija/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Vamos Variable",
    "tipo": "Variable",
    "tin": "2,00% (primer año)",
    "tae": "4,34% / 4,67%",
    "plazoMax": "25 años",
    "financiacionMax": "80%",
    "diferencial": "Desde el segundo año: E+0,60% / E+1,60%.",
    "vinculaciones": "Nómina ≥2.500 €/mes, 12 operaciones de tarjeta por semestre, 3 recibos, seguros de hogar y vida y 75 €/mes a fondos.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Desde 100.000 €; vivienda habitual. Ejemplo: 150.000 € a 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.ibercaja.es/particulares/hipotecas-prestamos/hipotecas/hipoteca-vamos-variable/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta 5 Vamos",
    "tipo": "Mixta",
    "tin": "2,00% / 3,00%",
    "tae": "3,86% / 4,17%",
    "plazoMax": "25 años",
    "financiacionMax": "80%",
    "diferencial": "Primer año: 2,00% en ambos casos; siguientes 4 años, el tipo indicado. Resto: E+0,60% / E+1,60%.",
    "vinculaciones": "Nómina ≥2.500 €/mes, 12 operaciones de tarjeta por semestre, 3 recibos, seguros de hogar y vida y 75 €/mes a fondos.",
    "comisiones": "Apertura 0%; reembolso en el tramo fijo: hasta 2%, limitado a la pérdida financiera.",
    "requisitos": "Desde 100.000 €; vivienda habitual. Ejemplo: 150.000 € a 25 años. Solicitudes hasta el 30/09/2026.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.ibercaja.es/particulares/hipotecas-prestamos/hipotecas/hipoteca-vamos-mixta-5/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Ibercaja Banco",
    "categoria": "Grande",
    "producto": "Hipoteca Mixta 10 Vamos",
    "tipo": "Mixta",
    "tin": "2,10% / 3,10%",
    "tae": "3,50% / 3,80%",
    "plazoMax": "25 años",
    "financiacionMax": "80%",
    "diferencial": "Primer año: 2,10% en ambos casos; siguientes 9 años, el tipo indicado. Resto: E+0,60% / E+1,60%.",
    "vinculaciones": "Nómina ≥2.500 €/mes, 12 operaciones de tarjeta por semestre, 3 recibos, seguros de hogar y vida y 75 €/mes a fondos.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Desde 100.000 €; vivienda habitual. Ejemplo: 150.000 € a 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.ibercaja.es/particulares/hipotecas-prestamos/hipotecas/hipoteca-vamos-mixta-10/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Grande",
    "producto": "Hipoteca Variable Kutxabank",
    "tipo": "Variable",
    "tin": "2,07% (primer año)",
    "tae": "3,82% / 4,46%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Desde el segundo año: E+0,49% / E+1,49%.",
    "vinculaciones": "Nómina, seguros y plan de pensiones/EPSV; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://clientes.kutxabank.es/es/hipotecas/variable.html",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Hipoteca Open Fija",
    "tipo": "Fija",
    "tin": "2,90% / 3,40%",
    "tae": "3,44% / 3,67%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Ejemplo a 30 años; primeros 3 meses al 2,90% en ambos casos. Otros plazos tienen tipos distintos.",
    "vinculaciones": "Nómina o ingresos y seguros de hogar y vida: hasta 0,50 puntos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 30 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.openbank.es/hipoteca-fija",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Hipoteca Open Mixta",
    "tipo": "Mixta",
    "tin": "2,80% / 3,30%",
    "tae": "3,81% / 4,03%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Tramo fijo: 5 años; primeros 3 meses al 2,80% en ambos casos. Resto: E+0,60% / E+1,10%.",
    "vinculaciones": "Nómina o ingresos y seguros de hogar y vida: hasta 0,50 puntos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.openbank.es/hipoteca-mixta",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Openbank",
    "categoria": "Online",
    "producto": "Hipoteca Open Variable",
    "tipo": "Variable",
    "tin": "2,00% / 2,50% (primer año)",
    "tae": "4,02% / 4,25%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Primeros 3 meses: 2,00% en ambos casos. Desde el segundo año: E+0,65% / E+1,15%.",
    "vinculaciones": "Nómina o ingresos y seguros de hogar y vida: hasta 0,50 puntos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.openbank.es/hipoteca-variable",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "Hipoteca Naranja Fija",
    "tipo": "Fija",
    "tin": "Personalizado",
    "tae": "Personalizada",
    "plazoMax": "25 años",
    "financiacionMax": "80% (segunda vivienda: 75% clientes / 65% no clientes)",
    "diferencial": "",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.ing.es/hipotecas/hipoteca-fija",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "Hipoteca Naranja Variable",
    "tipo": "Variable",
    "tin": "Personalizado",
    "tae": "Personalizada",
    "plazoMax": "40 años",
    "financiacionMax": "80% (segunda vivienda: 75% clientes / 65% no clientes)",
    "diferencial": "Mixta: 5, 10, 15 o 20 años fijos. Variable: 1 o 3 años fijos. Diferencial personalizado.",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura y amortización parcial 0%; la amortización total puede tener comisión si hay pérdida financiera. Consultar FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.ing.es/hipotecas/hipoteca-variable",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "ING",
    "categoria": "Online",
    "producto": "Hipoteca Naranja Mixta",
    "tipo": "Mixta",
    "tin": "Personalizado",
    "tae": "Personalizada",
    "plazoMax": "40 años",
    "financiacionMax": "80% (segunda vivienda: 75% clientes / 65% no clientes)",
    "diferencial": "Mixta: 5, 10, 15 o 20 años fijos. Variable: 1 o 3 años fijos. Diferencial personalizado.",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura y amortización parcial 0%; la amortización total puede tener comisión si hay pérdida financiera. Consultar FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.ing.es/hipotecas/hipoteca-mixta",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "COINC (Bankinter)",
    "categoria": "Online",
    "producto": "Hipoteca Variable COINC",
    "tipo": "Variable",
    "tin": "2,30% / 2,70%",
    "tae": "3,41% / 3,86%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (60% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "Tramo fijo: 3 años. Resto: E+0,50% / E+0,90%.",
    "vinculaciones": "Cuenta Nómina, Profesional o No-Nómina de Bankinter: bonificación de 0,40 puntos.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ejemplo: 150.000 € a 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.coinc.es/ahorrador/nuestras-hipotecas/hipoteca-variable",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "COINC (Bankinter)",
    "categoria": "Online",
    "producto": "Hipoteca Fija COINC",
    "tipo": "Fija",
    "tin": "2,99% / 3,39%",
    "tae": "3,28% / 3,75%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (60% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "Cuenta Bankinter",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Precios del ejemplo a 10 años; no extrapolables al plazo máximo de 30 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.coinc.es/ahorrador/nuestras-hipotecas/hipoteca-fija",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Pibank",
    "categoria": "Online",
    "producto": "Hipoteca Pibank Mixta",
    "tipo": "Mixta",
    "tin": "1,99%",
    "tae": "3,40%",
    "plazoMax": "35 años",
    "financiacionMax": "90% de compra (máximo 80% de tasación)",
    "diferencial": "Tramo fijo: 4 años. Resto: E+0,68%.",
    "vinculaciones": "Sin bonificaciones; cuenta operativa y seguro de daños, que puede contratarse con otra aseguradora.",
    "comisiones": "Sin comisiones de apertura ni amortización parcial o total.",
    "requisitos": "Al menos un titular funcionario o con contrato indefinido; ejemplo de 150.000 € a 25 años.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.pibank.es/hipotecas/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "MyInvestor",
    "categoria": "Online",
    "producto": "Hipoteca Sin Mochila Fija",
    "tipo": "Fija",
    "tin": "3,40%",
    "tae": "3,61%",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "SIN vinculaciones",
    "comisiones": "Apertura 0% para compra habitual hasta 80% y segunda vivienda hasta 70%; otras finalidades pueden tener 1%. Consultar FEIN.",
    "requisitos": "Ejemplo de nueva compra: 150.000 € a 30 años, sin comisión de apertura. Ingresos netos conjuntos mínimos: 4.000 €/mes.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://myinvestor.es/hipotecas/hipoteca-fija/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "MyInvestor",
    "categoria": "Online",
    "producto": "Hipoteca Sin Mochila Variable",
    "tipo": "Variable",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80% (70% segunda vivienda; sobre el menor valor de compra o tasación)",
    "diferencial": "",
    "vinculaciones": "SIN vinculaciones",
    "comisiones": "Apertura 0% para compra habitual hasta 80% y segunda vivienda hasta 70%; otras finalidades pueden tener 1%. Consultar FEIN.",
    "requisitos": "La web mezcla ejemplos de compra y subrogación y referencias de euríbor distintas; solicita el precio vigente para tu operación.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://myinvestor.es/hipotecas/hipoteca-variable/",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Banca March (Avantio)",
    "categoria": "Mediano",
    "producto": "Hipoteca Fija Avantio",
    "tipo": "Fija",
    "tin": "2,65% / 3,35%",
    "tae": "3,009% / 3,475%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Primer año: 2,65% en ambos casos; después, el tipo indicado.",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Nuevos clientes residentes; ingresos familiares ≥4.000 €/mes. Mínimo 200.000 € en compra o 150.000 € en subrogación. Ejemplo del simulador.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://avantio.bancamarch.es/es/simulador-de-hipoteca/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banca March (Avantio)",
    "categoria": "Mediano",
    "producto": "Hipoteca Avantio Mixta",
    "tipo": "Mixta",
    "tin": "2,85%",
    "tae": "3,648% / 3,969%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo: 5 años. Resto: E+0,75% / E+1,45%.",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Nuevos clientes residentes; ingresos familiares ≥4.000 €/mes. Mínimo 200.000 € en compra o 150.000 € en subrogación. Ejemplo del simulador.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://avantio.bancamarch.es/es/simulador-de-hipoteca/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Banca March (Avantio)",
    "categoria": "Mediano",
    "producto": "Hipoteca Avantio Variable",
    "tipo": "Variable",
    "tin": "2,75% (primer año)",
    "tae": "3,907% / 4,384%",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Desde el segundo año: E+0,75% / E+1,45%.",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Nuevos clientes residentes; ingresos familiares ≥4.000 €/mes. Mínimo 200.000 € en compra o 150.000 € en subrogación. Ejemplo del simulador.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://avantio.bancamarch.es/es/simulador-de-hipoteca/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Cajamar Caja Rural",
    "categoria": "Cooperativa",
    "producto": "HipotecON Fija",
    "tipo": "Fija",
    "tin": "2,85% / 3,65%",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "Socio (aportación mínima 61 €), nómina y recibos, banca electrónica, seguros de vida y hogar, tarjeta y ahorro/inversión.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Ingresos familiares ≥4.000 €/mes; endeudamiento ≤30%; préstamo superior a 60.000 €. TAE completa pendiente de confirmar.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.cajamar.es/es/particulares/productos-y-servicios/financiacion/hipotecas/hipoteca-tipo-fijo/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "imagin (CaixaBank)",
    "categoria": "Online",
    "producto": "Hipoteca Fija imaginBank",
    "tipo": "Fija",
    "tin": "3,05% / 3,80%",
    "tae": "3,774% / 4,288%",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "Nómina y seguros de hogar y vida; consultar requisitos de bonificación.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Préstamo concedido por CaixaBank. Ejemplo: 150.000 € a 25 años. Contratación desde la app.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.imagin.com/hipoteca/hipoteca-fija",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  },
  {
    "banco": "Deutsche Bank España",
    "categoria": "Mediano",
    "producto": "Hipotecas Variable y Mixta DB",
    "tipo": "Variable/Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.deutsche-bank.es/es/particulares/financiacion/hipotecas.html",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Banco Mediolanum",
    "categoria": "Mediano",
    "producto": "Hipotecas Freedom Variable / Mixta",
    "tipo": "Variable/Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.bancomediolanum.es/es/financiacion/hipotecas",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Caja de Ingenieros",
    "categoria": "Cooperativa",
    "producto": "Hipoteca Caja de Ingenieros",
    "tipo": "Fija/Variable/Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta para socios; la hipoteca joven tiene condiciones y plazos específicos.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.caixaenginyers.com/es/hipotecas",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Arquia Banca",
    "categoria": "Mediano",
    "producto": "Hipoteca Arquia",
    "tipo": "Fija/Variable/Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.arquia.com/particulares/hipotecas",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Kutxabank",
    "categoria": "Grande",
    "producto": "Hipoteca Fija Kutxabank",
    "tipo": "Fija",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://clientes.kutxabank.es/es/hipotecas/fija.html",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Hipotecas.com / UCI",
    "categoria": "Especialista",
    "producto": "Hipoteca VIVE UCI — Fija",
    "tipo": "Fija",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://uci.es/es/tipos-de-hipotecas/para-comprar-casa/",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Hipoteca Fija Laboral Kutxa",
    "tipo": "Fija",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "La entidad confirma las modalidades; solicita condiciones actuales en su simulador u oficina.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.laboralkutxa.com/es/personas/hipotecas-prueba/",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Hipotecas.com / UCI",
    "categoria": "Especialista",
    "producto": "Hipoteca VIVE UCI — Variable",
    "tipo": "Variable",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://uci.es/es/tipos-de-hipotecas/para-comprar-casa/",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Hipoteca Variable Laboral Kutxa",
    "tipo": "Variable",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "La entidad confirma las modalidades; solicita condiciones actuales en su simulador u oficina.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.laboralkutxa.com/es/personas/hipotecas-prueba/",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Hipotecas.com / UCI",
    "categoria": "Especialista",
    "producto": "Hipoteca VIVE UCI — Mixta",
    "tipo": "Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://uci.es/es/tipos-de-hipotecas/para-comprar-casa/",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Laboral Kutxa",
    "categoria": "Cooperativa",
    "producto": "Hipoteca Mixta Laboral Kutxa",
    "tipo": "Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "La entidad confirma las modalidades; solicita condiciones actuales en su simulador u oficina.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.laboralkutxa.com/es/personas/hipotecas-prueba/",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "CBNK (Banco Caminos / Bancofar)",
    "categoria": "Mediano",
    "producto": "Hipotecas CBNK",
    "tipo": "Fija/Variable/Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Banco Caminos y Bancofar operan bajo CBNK. Condiciones según perfil y colectivo.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.cbnk.es/personas/financiacion/Hipoteca",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Grupo Caja Rural (Ruralvía)",
    "categoria": "Cooperativa",
    "producto": "Hipotecas de las entidades del Grupo Caja Rural",
    "tipo": "Fija/Variable/Mixta",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Cada caja fija sus condiciones. Esta fila agrupa entidades y no representa un precio o una oferta única de todo el grupo.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.grupocajarural.es/es",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Caixa Ontinyent",
    "categoria": "Otro",
    "producto": "Préstamo hipoteca",
    "tipo": "Consultar",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.caixaontinyent.es/",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Colonya Caixa Pollença",
    "categoria": "Otro",
    "producto": "Préstamo Hipotecario",
    "tipo": "Consultar",
    "tin": "Consultar condiciones",
    "tae": "Consultar condiciones",
    "plazoMax": "",
    "financiacionMax": "",
    "diferencial": "",
    "vinculaciones": "",
    "comisiones": "Consultar apertura y reembolso anticipado en la FEIN.",
    "requisitos": "Oferta personalizada según perfil; solicita la FEIN.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://colonya.com/es/particulares/financiacion-particulares/prestamo-hipotecario",
    "fechaRevision": "2026-09-24",
    "estado": "consultar"
  },
  {
    "banco": "Cajamar Caja Rural",
    "categoria": "Cooperativa",
    "producto": "HipotecON Mixta",
    "tipo": "Mixta",
    "tin": "2,30% / 3,10%",
    "tae": "Consultar condiciones",
    "plazoMax": "30 años",
    "financiacionMax": "80%",
    "diferencial": "Tramo fijo: 5 años. Resto: E+0,60% / E+1,40%.",
    "vinculaciones": "Socio (aportación mínima 61 €), nómina y recibos, banca electrónica, seguros de vida y hogar, tarjeta y ahorro/inversión.",
    "comisiones": "Apertura 0%; consultar reembolso anticipado en la FEIN.",
    "requisitos": "Vivienda habitual; plazo 25–30 años; ingresos familiares ≥4.000 €/mes; endeudamiento ≤35%; préstamo superior a 60.000 €. TAE completa pendiente de confirmar.",
    "fuente": "Web oficial de la entidad",
    "urlFuente": "https://www.cajamar.es/es/particulares/productos-y-servicios/financiacion/hipotecas/hipoteca-tipo-mixto/",
    "fechaRevision": "2026-09-24",
    "estado": "publicada"
  }
]

export interface EntidadConsultada { banco: string; nota: string; fechaRevision: string; urlFuente?: string }
export const ENTIDADES_SIN_OFERTA: EntidadConsultada[] = [
  {
    "banco": "N26",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Revolut",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Trade Republic",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Bunq",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Wizink",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Banco Cetelem",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Singular Bank",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Andbank España",
    "nota": "Financiación a medida para clientes de banca privada; sin hipoteca minorista estándar",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Bankoa",
    "nota": "Integrado en Abanca",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Banco Cooperativo Español",
    "nota": "Banco mayorista del Grupo Caja Rural; no opera con particulares",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Banco BPI",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Novo Banco",
    "nota": "No comercializa hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Bank of China / ICBC",
    "nota": "Actividad corporativa; sin hipoteca minorista estándar en España",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Coop57",
    "nota": "Cooperativa de servicios financieros para entidades de economía social; no da hipotecas a particulares",
    "fechaRevision": "2026-08-24"
  },
  {
    "banco": "Cajasur Banco",
    "nota": "Integrado en Kutxabank; la integración tecnológica está completada. Consulta las ofertas de Kutxabank.",
    "urlFuente": "https://clientes.kutxabank.es/es/integracion/",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "EVO Banco",
    "nota": "Integrado en Bankinter desde julio de 2025; no se compara como una oferta independiente.",
    "urlFuente": "https://www.bankinter.com/banca/preguntas-frecuentes/migracion-evo-a-bankinter",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "Targobank",
    "nota": "Integrado en ABANCA; sus antiguas hipotecas no son ofertas independientes actuales.",
    "urlFuente": "https://comunicacion.abanca.com/es/noticias/abanca-finaliza-la-integracion-de-targobank-con-la-migracion-tecnologica-y-el-cambio-de-marca/",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "Triodos Bank",
    "nota": "Suspendida la contratación de nuevas hipotecas; mantiene el servicio de las ya contratadas.",
    "urlFuente": "https://www.triodos.es/es/centro-de-ayuda",
    "fechaRevision": "2026-09-24"
  }
]

export const OFERTAS_PENDIENTES: (EntidadConsultada & { producto: string })[] = [
  {
    "banco": "CaixaBank",
    "producto": "Hipoteca CasaFácil Mixto",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "CaixaBank",
    "producto": "Hipoteca CasaFácil Variable",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "BBVA",
    "producto": "Hipoteca Mixta BBVA",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "Kutxabank",
    "producto": "Hipoteca Mixta Kutxabank",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "COINC (Bankinter)",
    "producto": "Hipoteca Mixta COINC",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "Pibank",
    "producto": "Hipoteca Sin Comisiones Fija",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "Pibank",
    "producto": "Hipoteca Pibank Variable",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "MyInvestor",
    "producto": "Hipoteca Sin Mochila Mixta",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "Banco Pichincha España",
    "producto": "Hipoteca Banco Pichincha",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "Cajamar Caja Rural",
    "producto": "HipotecON Variable",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  },
  {
    "banco": "Fiare Banca Ética",
    "producto": "Financiación hipotecaria Fiare",
    "nota": "Entrada de agosto de 2026 cuya disponibilidad o condiciones actuales no se han confirmado. No se reutilizan sus cifras anteriores.",
    "fechaRevision": "2026-09-24"
  }
]
